-- FUP-AUTHZ-3 — keystones for the nine row-returning DEFINER doors the row-door sweep
-- found BLIND (ADR 0079 Amendment 4).
--
-- These nine came back BLIND from `supabase/tests/mutation/p0-authz-rowdoor-audit.sh`:
-- opening each door's identity guard (`if <cond> then` -> `if false then`) let a
-- non-member read another commission's content, and ALL 4903 assertions stayed green.
-- By CLAUDE.md's standing rule — a DEFINER's gate REPLACES RLS — the guard inside each
-- of these IS the entire boundary, so "no keystone exercises it" means the boundary was
-- untested, not lightly tested.
--
-- ⚠ EVERY ASSERTION IS A ROW COUNT THROUGH THE DOOR, never a predicate call. A correct
-- predicate is not a correct door (the three-shapes lesson): `app.is_member_of` can be
-- perfect while the door forgets to consult it. The only thing that proves a door is
-- shut is walking through it and counting what comes back.
--
-- ⚠ AND EVERY DENIAL HAS A NON-VACUITY TWIN. "the outsider reads 0 rows" is also true of
-- a door that returns 0 rows to EVERYONE — and then the assertion passes with the gate
-- wide open, which is precisely the failure this file exists to end. So each door is
-- asserted twice: the outsider reads 0 (or is refused), and the legitimate authority
-- reads the counts measured live on the seed (1, 3, 1, 15, 2, 3, 4, 1, 1 respectively).
-- If a seed change ever takes one of those to zero, the TWIN goes red here rather than
-- the denial silently becoming unfalsifiable.
--
-- THE DENIAL PRINCIPAL IS `chefe.farm` — staff_admin of commission B under the SAME
-- organization and hospital as commission A. Deliberately not an org-B user: a fully
-- foreign principal can be denied by the tenant boundary before the door's own gate is
-- reached, and the keystone would then be exercising cross-org isolation while claiming
-- to pin the commission gate (ARCHITECTURE.md's reader-non-writer rule, same shape).
-- chefe.farm is a legitimate, same-tenant, authenticated user who simply is not in A.
--
-- Mutation oracle (how these were proven able to fail): re-run
-- `p0-authz-rowdoor-audit.sh`. EIGHT of the nine move BLIND -> COVERED; reverting this
-- file returns them to BLIND. The ninth, `get_case_meeting_links`, stayed BLIND — see
-- §1.6: its guard is backstopped by a second gate inside its own query, so no assertion
-- through that door can red when the guard opens. That was found BY the sweep, not by
-- reading this file, which is exactly why the oracle is the sweep and not review.
--
-- Assertion count: 18

begin;
select plan(18);

-- Flags on: several of these doors open with `perform app.assert_<feature>_enabled()`,
-- and a door behind a disabled flag raises before its gate is ever consulted — the
-- fixture-flag gap that makes a keystone SKIP while reporting nothing.
update app.feature_flags set enabled = true;

create temp table k on commit drop as select
  '00000000-0000-0000-0000-000000000002'::uuid as chefe_ccih,  -- staff_admin of A (CCIH)
  '00000000-0000-0000-0000-000000000005'::uuid as chefe_farm,  -- staff_admin of B, NOT in A
  'a0000000-0000-0000-0000-0000000000a1'::uuid as comm_a,      -- Comissão CCIH (org A)
  'd0000000-0000-0000-0000-0000000000c1'::uuid as case_a,      -- a case of A, linked to a meeting
  'e1000000-0000-0000-0000-0000000000a1'::uuid as event_a;     -- a patient-safety event
-- The indicator id is generated by the seed, not fixed: resolve it, never hardcode it.
create temp table ind on commit drop as
  select id from public.indicators where commission_id = 'a0000000-0000-0000-0000-0000000000a1' limit 1;
grant select on k, ind to authenticated;

-- ============================================================================
-- §1 THE OUTSIDER. chefe.farm is authenticated and legitimate, but is not a member,
--    staff_admin or commission_admin of A. Every door must give up nothing.
--    Seven return empty; two raise (their guards deny with an exception, not a return).
-- ============================================================================
select test_helpers.claims_for((select chefe_farm from k), false);
set local role authenticated;

select is(
  (select count(*)::int from public.documents_due_for_review((select comm_a from k))), 0,
  '1.1 documents_due_for_review: an outsider reads 0 (gate open: 1)');
select is(
  (select count(*)::int from public.indicator_kpis((select comm_a from k))), 0,
  '1.2 indicator_kpis: an outsider reads 0 (gate open: 1)');
select is(
  (select count(*)::int from public.indicator_series((select id from ind), null, null)), 0,
  '1.3 indicator_series: an outsider reads 0 measurements of A''s indicator (gate open: 4)');
select is(
  (select count(*)::int from public.list_addable_commission_members((select comm_a from k), null)), 0,
  '1.4 list_addable_commission_members: an outsider enumerates 0 of A''s addable users (gate open: 15)');
select is(
  (select count(*)::int from public.list_commission_documents((select comm_a from k))), 0,
  '1.5 list_commission_documents: an outsider reads 0 of A''s controlled documents (gate open: 2)');
-- ⚠ 1.6 IS NOT A KEYSTONE FOR THIS DOOR'S GUARD, and saying so is the point. Every
-- other assertion in §1 reds when its guard is opened; this one does not, and the sweep
-- said so — `get_case_meeting_links` came back BLIND on the run that flipped the other
-- eight to COVERED. Measured directly: with `can_read_case` rewritten to `if false then`,
-- the outsider STILL reads 0, because the query carries a second, independent gate
-- (`app.can_reach_meeting(mc.meeting_id, v_uid)`) that enforces the same boundary. The
-- outer guard is therefore defense-in-depth, and NO row-count assertion through this
-- door can distinguish its presence from its absence. It is allowlisted as a genuine
-- backstop in authz-blind-allowlist.txt with that measurement as the justification.
-- The assertion stays because the BEHAVIOUR is worth pinning — an outsider must read
-- nothing here, whichever gate does the work — but calling it a keystone would be the
-- "7 keystones that could not fail" error committed in the file that exists to end it.
select is(
  (select count(*)::int from public.get_case_meeting_links((select case_a from k))), 0,
  '1.6 get_case_meeting_links: an outsider reads 0 meeting links (held by can_reach_meeting, NOT by the guard)');
select is(
  (select count(*)::int from public.triage_disposition((select event_a from k))), 0,
  '1.7 triage_disposition: an outsider reads 0 triage rows for the event (gate open: 1)');

-- ⚠ PINNED TO THE ERRCODE, not to "throws anything". A bare `throws_ok(.., null, null)`
-- passes on ANY exception — a disabled flag, a null argument, a typo in the fixture —
-- so it would report the gate as held while proving only that the call failed somehow.
-- These two codes are the authorization refusals specifically ('42501' and the domain
-- code 'HC071'), so the assertion can only pass for the reason it claims.
select throws_ok(
  format($$select * from public.evidence_candidates(%L, 'form', null)$$, (select comm_a from k)),
  '42501', null,
  '1.8 evidence_candidates: an outsider is REFUSED 42501 (this guard raises, it does not return empty)');
select throws_ok(
  format($$select * from public.list_referral_target_commissions(%L)$$, (select comm_a from k)),
  'HC071', null,
  '1.9 list_referral_target_commissions: an outsider is REFUSED HC071 (guard raises)');
reset role;

-- ============================================================================
-- §2 THE NON-VACUITY TWINS. Each count below was measured live against the seed. A
--    door that has quietly stopped returning anything makes its §1 denial pass for the
--    wrong reason, so these are not "nice to have" — they are what keeps §1 falsifiable.
-- ============================================================================
select test_helpers.claims_for((select chefe_ccih from k), false);
set local role authenticated;

select cmp_ok(
  (select count(*)::int from public.documents_due_for_review((select comm_a from k))), '>', 0,
  '2.1 TWIN: the staff_admin of A DOES read documents due for review');
select cmp_ok(
  (select count(*)::int from public.indicator_kpis((select comm_a from k))), '>', 0,
  '2.2 TWIN: the staff_admin of A DOES read indicator KPIs');
select cmp_ok(
  (select count(*)::int from public.indicator_series((select id from ind), null, null)), '>', 0,
  '2.3 TWIN: the staff_admin of A DOES read the indicator series');
select cmp_ok(
  (select count(*)::int from public.list_addable_commission_members((select comm_a from k), null)), '>', 0,
  '2.4 TWIN: the staff_admin of A DOES enumerate addable members');
select cmp_ok(
  (select count(*)::int from public.list_commission_documents((select comm_a from k))), '>', 0,
  '2.5 TWIN: the staff_admin of A DOES read the commission documents');
select cmp_ok(
  (select count(*)::int from public.get_case_meeting_links((select case_a from k))), '>', 0,
  '2.6 TWIN: the staff_admin of A DOES read the case''s meeting links');
select cmp_ok(
  (select count(*)::int from public.triage_disposition((select event_a from k))), '>', 0,
  '2.7 TWIN: the staff_admin of A DOES read the event''s triage disposition');
select cmp_ok(
  (select count(*)::int from public.evidence_candidates((select comm_a from k), 'form', null)), '>', 0,
  '2.8 TWIN: the staff_admin of A DOES get evidence candidates');
select cmp_ok(
  (select count(*)::int from public.list_referral_target_commissions((select comm_a from k))), '>', 0,
  '2.9 TWIN: the staff_admin of A DOES get referral targets');
reset role;

select * from finish();
rollback;
