-- 400_data_access_census — the LIVE half of the generated data-access surface.
--
-- ⚙ GENERATED by scripts/gen-data-access-surface.mjs. Rebuild with
--   npm run data-access:surface
-- ⛔ Do not hand-edit: gate 17 (`npm run lint:data-access`) compares the pins below
-- against the anchors in docs/backend-state/generated-*.md WITHOUT a database, and
-- compares the SQL spliced here against scripts/data-access-census.sql byte for byte.
--
-- WHAT THIS SUITE IS FOR, stated so a green is not over-read:
--   doc == pin      is gate 17's claim   (text only, in `npm run lint`)
--   pin == catalog  is THIS suite's claim (live, in `npm run test:db`)
-- Neither half alone says the doc matches the catalog. Together they do.
--
-- ⚠ WHEN THIS REDS AFTER A MIGRATION IT IS USUALLY RIGHT AND THE REMEDY IS ONE COMMAND:
-- `npm run data-access:surface`, then commit the regenerated files. That is the same
-- discipline Architecture Rule 8 already imposes for `npm run gen:types`.
-- ⛔ Never edit a pin to match a changed catalog without regenerating the doc: the pin and
-- the doc are two homes for one number, and un-syncing them is exactly what gate 17 exists
-- to catch.
--
-- ⚠ `app.feature_flags.enabled` IS NOT PINNED, on purpose. It is seeded ON locally and the
-- production value is a different fact; pinning it would red on every seed change while
-- proving nothing about the deployment anybody cares about.

begin;
select plan(6);

create temporary table _dac_live (kind text, rows bigint, digest text);

-- ⛔ THE ROW EXPRESSION BELOW IS SPLICED, VERBATIM, FROM scripts/data-access-census.sql.
-- Gate 17 re-extracts it and compares byte for byte, so this copy cannot drift from the
-- census the documentation was generated with. Editing it here reds gate 17.
insert into _dac_live (kind, rows, digest)
select case when l like 'FUNC|public|%' then 'rpc' else 'helper' end,
       count(*),
       md5(string_agg(l, chr(10) order by l collate "C"))
from (
  select 'FUNC|' || n.nspname
         || '|' || p.proname
         || '|' || pg_get_function_identity_arguments(p.oid)
         || '|' || pg_catalog.format_type(p.prorettype, null)
         || '|' || case p.prosecdef when true then 'definer' else 'invoker' end
         || '|' || case p.provolatile when 'i' then 'immutable'
                                      when 's' then 'stable'
                                      else 'volatile' end
         || '|' || case when p.prorettype = 'trigger'::regtype then 'trigger' else 'function' end
         || '|' || coalesce(
                     (select string_agg(x::text, ',' order by x::text) from unnest(p.proacl) x),
                     '<NULL=PUBLIC>')
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname in ('public','app')
    and p.prokind = 'f'
) s(l)
group by 1;

insert into _dac_live (kind, rows, digest)
select 'flags', count(*), md5(string_agg(l, chr(10) order by l collate "C"))
from (
  select 'FLAG|' || f.key
         || '|' || f.enabled::text
         || '|' || replace(replace(coalesce(f.description, ''), '|', '/'), chr(10), ' ')
  from app.feature_flags f
) s(l);

-- The pins, generated from the same census that produced the documentation.
create temporary table _dac_pin (kind text, rows bigint, digest text);
insert into _dac_pin (kind, rows, digest) values
  ('rpc', 555, '90de15fbe48e1250668ae9516070c9aa'),
  ('helper', 526, '5a4a5161f9c3830e7e267ab3f930ea5d'),
  ('flags', 43, 'e5ae44b11aa59c918274e3b15411bd6b');

select is(
  (select rows from _dac_live where kind = 'rpc'),
  (select rows from _dac_pin  where kind = 'rpc'),
  'rpc: the live catalog holds the pinned number of rows — if this reds, run npm run data-access:surface'
);
select is(
  (select digest from _dac_live where kind = 'rpc'),
  (select digest from _dac_pin  where kind = 'rpc'),
  'rpc: the live catalog digests to the pinned value — a rename, an ACL change or a prosecdef flip reds here even when the COUNT is unchanged'
);
select is(
  (select rows from _dac_live where kind = 'helper'),
  (select rows from _dac_pin  where kind = 'helper'),
  'helper: the live catalog holds the pinned number of rows — if this reds, run npm run data-access:surface'
);
select is(
  (select digest from _dac_live where kind = 'helper'),
  (select digest from _dac_pin  where kind = 'helper'),
  'helper: the live catalog digests to the pinned value — a rename, an ACL change or a prosecdef flip reds here even when the COUNT is unchanged'
);
select is(
  (select rows from _dac_live where kind = 'flags'),
  (select rows from _dac_pin  where kind = 'flags'),
  'flags: the live catalog holds the pinned number of rows — if this reds, run npm run data-access:surface'
);
select is(
  (select digest from _dac_live where kind = 'flags'),
  (select digest from _dac_pin  where kind = 'flags'),
  'flags: the live catalog digests to the pinned value — a rename, an ACL change or a prosecdef flip reds here even when the COUNT is unchanged'
);

select * from finish();
rollback;
