#!/usr/bin/env bash
# Generated by scripts/worktree-setup.sh — runs this worktree's dev server on
# its assigned port (PORT can't be set via .env files; Next only reads it
# from the environment).
exec env PORT=3001 npm run dev
