import { readFileSync } from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  ROLE_LABELS,
  ROLE_MANIFEST,
  ROLE_ORDER,
  ROLE_SCOPE_KIND,
} from '@/lib/role/role-catalog'
// ⚠ A TEST importing from `src/components` — deliberate, and not the layering inversion
// role-catalog.ts's header warns about. That warning is about a `src/lib/queries` MODULE
// taking a runtime dependency on components; this is a gate reaching for the map it
// binds, and the map is a pure pt-BR label object with no client boundary.
import { ROLE_LABELS as BLOCKER_ROLE_LABELS } from '@/components/users/affiliation-blocker-label'

/**
 * ⭐ AE4.8 [PA-F1], split at AE4.9 "do now" item (d) / audit finding IA-F7.
 *
 * WHY THIS FILE USED TO SHELL OUT TO DOCKER, AND WHY IT NO LONGER DOES.
 * The original guard read `authz.roles` through `docker exec … psql` so that
 * `ROLE_MANIFEST` could never drift from the live catalog without a test noticing (ADR
 * 0155 G4's "typed query" ask is not implementable — `authz` is deliberately outside
 * every client role's reach; see `role-catalog.ts`'s `isPlatformRole` doc comment for
 * the full reasoning). That bound `npm run test` (a unit-test run) to Docker being up,
 * which is a database dependency a *unit* suite must not carry.
 *
 * IA-F7 splits the guard by what each half actually needs:
 *   - Provable from `ROLE_MANIFEST`/`ROLE_LABELS`/`ROLE_SCOPE_KIND`/`BLOCKER_ROLE_LABELS`
 *     alone, with no I/O beyond reading this repo's own committed text — stays HERE.
 *   - Needs the live `authz.roles` catalog — moved to the pgTAP suite
 *     `supabase/tests/411_ae48_role_manifest_db_gate.sql`, which runs post-`db reset`
 *     as part of the DB gate, not as a unit test.
 *
 * THE CROSS-LANGUAGE SEAM. `ROLE_MANIFEST` is TypeScript; pgTAP is SQL; neither side can
 * import the other. The shared, machine-checkable stand-in is a COMMITTED, GENERATED
 * artifact — `supabase/tests/vectors/role_manifest.psql`, written by
 * `scripts/gen-role-manifest.mjs --write` from the LIVE catalog — that both sides key on:
 *   - THIS file reads it as plain text (`fs.readFileSync`, no DB, no Docker) and asserts
 *     it equals `ROLE_MANIFEST` — see the last test below.
 *   - 411 asserts that SAME artifact against the live `authz.roles` table.
 * Neither hop alone re-proves the original claim ("ROLE_MANIFEST is the live role
 * catalog"); chained, they do, and each hop can red independently on its own half of a
 * drift (edit `ROLE_MANIFEST` without regenerating → this file reds; edit a migration's
 * role seed without regenerating → 411 reds).
 *
 * ⭐ IT USED TO BE A HAND-TYPED BLOCK INSIDE 411, between `MANIFEST-SNAPSHOT-BEGIN`/`END`
 * markers, and 411's own comment conceded that *"nothing enforces the edit itself; a code
 * review noticing 'ROLE_MANIFEST changed, did 411 move too' is still the first line of
 * defense."* ADR 0207 D4 replaced it with the generated artifact, and the hand-edit — and
 * with it the only step a human had to remember — is gone.
 *
 * ⚠ AND THERE ARE NOW TWO TS-SIDE READERS, WHICH IS NOT REDUNDANCY. Gate 19
 * (`gen-role-manifest.mjs --check`, in `npm run lint`) compares the artifact to
 * ROLE_MANIFEST by PARSING `role-catalog.ts` as text; it never evaluates the module, so a
 * parser that read the source wrongly would agree with itself. The test below compares the
 * artifact to the REAL EVALUATED objects. Each can catch what the other cannot.
 *
 * ⚠ THE CATALOG IS STILL READ AT (DB) GATE TIME, NOT TRANSCRIBED BY HAND INTO A SECOND
 * TS FILE. The recorded rule is that an enumeration's boundary must be the PROPERTY,
 * never a remembered list — every instance of the landing-seam class so far has been
 * someone updating one list and not the other. This is the sibling of
 * `session-grants.test.ts`'s FUP-QO-2 guard, which binds the same manifest to
 * `memberships_role_check` from the other side.
 */

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')

const ARTIFACT_RELATIVE_PATH = path.join(
  'supabase',
  'tests',
  'vectors',
  'role_manifest.psql',
)

/**
 * Parse the GENERATED role-catalog artifact — see the module doc comment above. Plain-text
 * `fs.readFileSync` of a file already checked into THIS repo: no DB connection, no Docker,
 * no network. This is what lets the drift check below run in the same process as every
 * other unit test.
 */
function readManifestArtifact(): Array<{
  code: string
  scopeKind: string
  sessionSelectable: boolean
}> {
  const artifactPath = path.join(REPO_ROOT, ARTIFACT_RELATIVE_PATH)
  const text = readFileSync(artifactPath, 'utf8').replace(/\r\n/g, '\n')

  const marker = 'insert into role_manifest_pin'
  const start = text.indexOf(marker)
  if (start === -1) {
    throw new Error(
      `role-catalog artifact guard: could not find "${marker}" in ` +
        `${ARTIFACT_RELATIVE_PATH}. The artifact is generated by ` +
        '`node scripts/gen-role-manifest.mjs --write`; if its shape changed, this parser ' +
        'and gate 19 both need moving.',
    )
  }

  // Each row is `  ('code', 'scope_kind', <selectable>, <system_managed>, 'state')`.
  const rowPattern =
    /^ {2}\('([a-z_]+)', '([a-z_]+)', (true|false), (?:true|false), '[a-z_]+'\),?;?$/gm
  const rows: Array<{ code: string; scopeKind: string; sessionSelectable: boolean }> = []
  let match: RegExpExecArray | null
  const body = text.slice(start)
  while ((match = rowPattern.exec(body)) !== null) {
    rows.push({
      code: match[1],
      scopeKind: match[2],
      sessionSelectable: match[3] === 'true',
    })
  }

  if (rows.length === 0) {
    throw new Error(
      `role-catalog artifact guard: parsed ZERO rows out of ${ARTIFACT_RELATIVE_PATH}. ` +
        'An empty artifact would make the comparison below vacuous.',
    )
  }
  return rows
}

describe('role-catalog manifest — pure checks + the generated-artifact binding', () => {
  it('the manifest covers every PlatformRole code — ROLE_ORDER is not exhaustive by type', () => {
    // ⛔ `as const satisfies readonly PlatformRole[]` does NOT catch a MISSING role: a
    // short array still satisfies the constraint. ROLE_LABELS is exhaustive by type, so
    // comparing against its keys is the check the type system cannot make.
    expect([...ROLE_ORDER].sort()).toEqual(Object.keys(ROLE_LABELS).sort())
    expect(ROLE_MANIFEST).toHaveLength(Object.keys(ROLE_LABELS).length)
    expect(new Set(ROLE_ORDER).size).toBe(ROLE_ORDER.length)
  })

  it('the affiliation-blocker label map covers the same roles — SHARED KEYS, OWN WORDING', () => {
    // ⭐ AE4.8's first bullet, as RULED rather than as written. The plan said "the six
    // label maps collapse into ROLE_LABELS re-exports". Measured, there are no six: the
    // Interviewer/Attendee/RcaMember maps key on unrelated enums, and the two that DO key
    // on platform roles carry deliberately DIFFERENT pt-BR vocabularies —
    // "Coordenação" here vs "Coordenador(a) de comissão" in the picker. Collapsing the
    // TEXT would have changed user-facing copy in an increment specified as
    // behaviour-preserving, and broken the fixture that pins the current wording.
    //
    // ⛔ So the binding is on the KEY SET only. Adding a role to the manifest now fails
    // here until it is named in the blocker map too — which is the actual defect the
    // bullet was aimed at (that module's own header records shipping a blocker rendered
    // as a nameless empty label). The wording stays that module's to own.
    //
    // ⚠ `platform_admin` is excluded BY PROPERTY, not by exception: blockers come from
    // `memberships`, and platform_admin lives in `profiles.is_admin` and never holds a
    // memberships row (D11), so a label for it there could never render.
    const expected = ROLE_ORDER.filter((c) => c !== 'platform_admin').sort()
    expect(Object.keys(BLOCKER_ROLE_LABELS).sort()).toEqual(expected)
  })

  it('ROLE_SCOPE_KIND is defined for exactly the manifest roles (cardinality control)', () => {
    // Ported from the old "ROLE_SCOPE_KIND holds only values the catalog vocabulary
    // uses" test's non-DB half. Its OTHER half — no scope kind is a stranger to
    // `authz.roles.allowed_scope_kind`'s real vocabulary — needs the live catalog and
    // now lives in 411 §5; this half needs nothing but the TS objects themselves, and
    // guards against ROLE_SCOPE_KIND being shorter than ROLE_ORDER, which would make
    // 411 §5's vocabulary-subset check meaningful over a silently-shrunken set.
    expect(Object.keys(ROLE_SCOPE_KIND).length).toBe(ROLE_ORDER.length)
  })

  it('every role sharing a landing branch declares the same empty fallback', () => {
    // ⭐ THE ONE MANIFEST FACT THE TYPE SYSTEM CANNOT HOLD. `branchEmptyFallback` is
    // declared PER ROLE but consumed PER BRANCH: role-catalog.ts derives
    // BRANCH_EMPTY_FALLBACK by keying the manifest on `branch`, so if two roles sharing a
    // branch disagreed, the last one declared would silently win and the other role's
    // stated fallback would never be used. Nothing in the types says they must agree.
    //
    // ⚠ This is a NEW obligation created by the F7 collapse: before it, the table was
    // hand-written per branch and the question could not arise. It is asserted here rather
    // than thrown at import time because this module is imported by three "use client"
    // components, and a module-level throw would take the page down instead of the build.
    const byBranch = new Map<string, Set<string>>()
    for (const entry of ROLE_MANIFEST) {
      const seen = byBranch.get(entry.branch) ?? new Set<string>()
      seen.add(entry.branchEmptyFallback)
      byBranch.set(entry.branch, seen)
    }
    const disagreeing = [...byBranch.entries()]
      .filter(([, fallbacks]) => fallbacks.size > 1)
      .map(([branch, fallbacks]) => `${branch}: ${[...fallbacks].join(' vs ')}`)
    expect(disagreeing).toEqual([])

    // Cardinality control: a manifest that somehow produced no branches at all would pass
    // the emptiness assertion above while measuring nothing.
    expect(byBranch.size).toBeGreaterThan(0)
  })

  it('ROLE_MANIFEST matches the generated artifact that 411 binds to the live catalog', () => {
    // ⭐ THE DRIFT CHECK. This is the TS-side hop of the two-hop chain described in the
    // module doc comment: it proves ROLE_MANIFEST agrees with the COMMITTED artifact
    // (plain text, no DB); 411 proves that SAME artifact agrees with the live
    // `authz.roles` catalog (DB, post-`db reset`). Together they re-prove what the old
    // single Docker-shelling test proved — that ROLE_MANIFEST is exactly the role catalog,
    // with matching scope kinds — without either hop acquiring the other's dependency.
    //
    // ⚠ THIS IS NOT A DUPLICATE OF GATE 19, and the difference is the point. Gate 19
    // (`gen-role-manifest.mjs --check`) compares the artifact to ROLE_MANIFEST by PARSING
    // role-catalog.ts AS TEXT — it never evaluates the module, so a parser that read the
    // source wrongly would agree with itself. This test compares the artifact to the REAL
    // EVALUATED objects, after `as const`, after every derivation. Two readers, one of
    // which cannot be fooled by the other's parse.
    //
    // ⛔ Edit ROLE_MANIFEST (add/remove a role, change a scopeKind) without regenerating
    // the artifact, or vice versa, and THIS test reds — no `supabase start` required.
    const artifact = readManifestArtifact()
    const fromManifest = [...ROLE_MANIFEST]
      .map((r) => ({
        code: r.code as string,
        scopeKind: r.scopeKind as string,
        sessionSelectable: r.sessionSelectable as boolean,
      }))
      .sort((a, b) => a.code.localeCompare(b.code))
    const fromArtifact = [...artifact].sort((a, b) => a.code.localeCompare(b.code))

    // Cardinality control first: a truncated artifact would make the equality below
    // pass on a subset instead of the whole manifest.
    expect(artifact.length).toBe(ROLE_MANIFEST.length)
    expect(fromArtifact).toEqual(fromManifest)
  })
})
