import { createClient } from '@/lib/supabase/server'

/**
 * Case ACTION ITEMS data-access (Cases-Extras batch, R4) — systemic-improvement
 * follow-ups generated by a case (Architecture Rule 9). A case has ONE macro
 * status (R2) AND MANY action-item rows; this is distinct from the case status.
 *
 * `case_action_items` carries a light status lifecycle
 * (`open`/`in_progress`/`done`/`cancelled`), an optional assignee + due date,
 * and an optional `source_case_phase_id` (the phase whose review generated it,
 * `ON DELETE SET NULL`). Commission is derived via the case (not denormalized),
 * matching `case_phases`. RLS member-read / staff_admin full-write; assignees
 * advance their OWN items via a narrow RPC (not a broad UPDATE policy).
 */

/** Action-item lifecycle status. */
export type ActionItemStatus = 'open' | 'in_progress' | 'done' | 'cancelled'

/** One systemic-improvement action item attached to a case. */
export interface CaseActionItem {
  id: string
  caseId: string
  /** The phase whose review generated this, if any (`null` once that phase is
   * deleted, or if created free-standing). */
  sourceCasePhaseId: string | null
  title: string
  description: string | null
  status: ActionItemStatus
  assignedTo: string | null
  /** Assignee's display name (joined); `null` if unassigned/unresolved. */
  assigneeName: string | null
  /** ISO `YYYY-MM-DD`; `null` = no due date. Past + not done/cancelled = overdue. */
  dueDate: string | null
  createdBy: string | null
  createdAt: string
  updatedAt: string
  completedAt: string | null
  completedBy: string | null
}

/** Open / overdue / completed-YTD counts for the KPI strip & dashboards. */
export interface CaseActionItemKpis {
  /** Items in `open` or `in_progress`. */
  open: number
  /** Open items whose `due_date` is in the past. */
  overdue: number
  /** Items completed (`done`) this calendar year. */
  completedYtd: number
}

// ---------------------------------------------------------------------------
// Row shapes
// ---------------------------------------------------------------------------

interface ActionItemRow {
  id: string
  case_id: string
  source_case_phase_id: string | null
  title: string
  description: string | null
  status: ActionItemStatus
  assigned_to: string | null
  due_date: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  completed_at: string | null
  completed_by: string | null
  profiles: { full_name: string | null } | null
}

interface ActionItemKpisRow {
  open: number
  overdue: number
  completed_ytd: number
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/**
 * The action items of one case (the per-case panel). RLS-scoped (members read);
 * `[]` when unreadable. Ordered: still-open work first, then by due date (soonest
 * first, nulls last), then newest. The assignee's name is joined via the
 * member-readable `profiles`.
 */
export async function listCaseActionItems(
  caseId: string,
): Promise<CaseActionItem[]> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('case_action_items')
    .select(
      `
      id, case_id, source_case_phase_id, title, description, status,
      assigned_to, due_date, created_by, created_at, updated_at,
      completed_at, completed_by,
      profiles:assigned_to ( full_name )
    `,
    )
    .eq('case_id', caseId)
    .order('due_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: false })
    .returns<ActionItemRow[]>()

  if (error || !data) return []

  return data.map((r) => ({
    id: r.id,
    caseId: r.case_id,
    sourceCasePhaseId: r.source_case_phase_id,
    title: r.title,
    description: r.description,
    status: r.status,
    assignedTo: r.assigned_to,
    assigneeName: r.profiles?.full_name ?? null,
    dueDate: r.due_date,
    createdBy: r.created_by,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    completedAt: r.completed_at,
    completedBy: r.completed_by,
  }))
}

/**
 * Action-item KPIs for a commission (open / overdue / completed-YTD). Backed by
 * the SECURITY DEFINER `case_action_items_kpis`, internally `is_staff_admin_of`-
 * gated. Returns zeroed counts for a non-staff_admin (no leak).
 */
export async function getCaseActionItemKpis(
  commissionId: string,
): Promise<CaseActionItemKpis> {
  const zero: CaseActionItemKpis = { open: 0, overdue: 0, completedYtd: 0 }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('case_action_items_kpis', {
    p_commission_id: commissionId,
  })

  if (error || !data) return zero

  const row = (data as unknown as ActionItemKpisRow[])[0]
  if (!row) return zero

  return {
    open: Number(row.open),
    overdue: Number(row.overdue),
    completedYtd: Number(row.completed_ytd),
  }
}
