import { createClient } from '@/lib/supabase/server'
import type { VisibilityScope } from '@/lib/queries/action-items'

/**
 * Case ACTION ITEMS data-access — systemic-improvement follow-ups generated by a
 * case (Architecture Rule 9). A case has ONE macro status AND MANY action-item
 * rows; this is distinct from the case status.
 *
 * As of the case-fold migration (20260707), case action items live on the SHARED
 * `public.action_items` hub as `source_type = 'case'` rows (linked via
 * `source_case_id`), NOT the old `case_action_items` table (dropped). The row is
 * always `visibility_scope = 'case_restricted'` (guard-forced), so RLS follows
 * `app.can_read_case` — a plain member no longer sees a restricted case's items.
 *
 * The public shape below is UNCHANGED so the panel keeps working: a light status
 * lifecycle keyed `open`/`in_progress`/`done`/`cancelled` (the joined status
 * KEY), an optional assignee + due date, and an optional `sourceCasePhaseId` (the
 * phase whose review generated it, `ON DELETE SET NULL`). Writes go through the
 * `committee_*` RPCs (see `src/lib/cases/action-items-actions.ts`).
 */

/** Action-item lifecycle status (the hub status KEY). */
export type ActionItemStatus = 'open' | 'in_progress' | 'done' | 'cancelled'

/** One systemic-improvement action item attached to a case. */
export interface CaseActionItem {
  id: string
  caseId: string
  /** The phase whose review generated this, if any (`null` once that phase is
   * deleted, or if created free-standing). */
  sourceCasePhaseId: string | null
  title: string
  description: string | null
  status: ActionItemStatus
  /**
   * Per-row read scope (ADR 0050). Always `'case_restricted'` for a case-sourced
   * row (guard-forced); projected for type/UI parity (§4.2) rather than asserted
   * only in a comment.
   */
  visibilityScope: VisibilityScope
  assignedTo: string | null
  /** Assignee's display name (joined); `null` if unassigned/unresolved. */
  assigneeName: string | null
  /** ISO `YYYY-MM-DD`; `null` = no due date. Past + not done/cancelled = overdue. */
  dueDate: string | null
  createdBy: string | null
  createdAt: string
  updatedAt: string
  completedAt: string | null
  completedBy: string | null
}

/** Open / overdue / completed-YTD counts for the KPI strip & dashboards. */
export interface CaseActionItemKpis {
  /** Items in a non-terminal status (`open` or `in_progress`). */
  open: number
  /** Open items whose `due_date` is in the past. */
  overdue: number
  /** Items completed (`done`) this calendar year. */
  completedYtd: number
}

// ---------------------------------------------------------------------------
// Row shapes
// ---------------------------------------------------------------------------

/**
 * A case-sourced hub row + its joined status key + assignee name. The embedded
 * `action_item_statuses` join yields the client-facing `key`; the `assignee`
 * alias resolves the display name via the member-readable `profiles` (the
 * `assigned_to` FK, disambiguated from the other profile FKs).
 */
interface HubActionItemRow {
  id: string
  source_case_id: string
  source_case_phase_id: string | null
  title: string
  description: string | null
  visibility_scope: VisibilityScope
  status: { key: ActionItemStatus } | null
  assigned_to: string | null
  due_date: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  completed_at: string | null
  completed_by: string | null
  assignee: { full_name: string | null } | null
}

interface ActionItemKpisRow {
  open: number
  overdue: number
  completed_ytd: number
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/**
 * The action items of one case (the per-case panel). Reads the shared hub
 * (`source_type = 'case' AND source_case_id = caseId`); RLS-scoped via the
 * case_restricted policy (`app.can_read_case`), so `[]` when unreadable. Ordered:
 * still-open work first, then by due date (soonest first, nulls last), then
 * newest. The status KEY and assignee name are joined.
 */
export async function listCaseActionItems(
  caseId: string,
): Promise<CaseActionItem[]> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('action_items')
    .select(
      `
      id, source_case_id, source_case_phase_id, title, description,
      visibility_scope, assigned_to, due_date, created_by, created_at, updated_at,
      completed_at, completed_by,
      status:action_item_statuses!action_items_status_fkey ( key ),
      assignee:profiles!action_items_assigned_to_fkey ( full_name )
    `,
    )
    .eq('source_type', 'case')
    .eq('source_case_id', caseId)
    .order('due_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: false })
    .returns<HubActionItemRow[]>()

  if (error || !data) return []

  return data.map((r) => ({
    id: r.id,
    caseId: r.source_case_id,
    sourceCasePhaseId: r.source_case_phase_id,
    title: r.title,
    description: r.description,
    // The status FK is NOT NULL in the schema; fall back to 'open' defensively.
    status: r.status?.key ?? 'open',
    visibilityScope: r.visibility_scope,
    assignedTo: r.assigned_to,
    assigneeName: r.assignee?.full_name ?? null,
    dueDate: r.due_date,
    createdBy: r.created_by,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    completedAt: r.completed_at,
    completedBy: r.completed_by,
  }))
}

/**
 * Action-item KPIs for a commission (open / overdue / completed-YTD). Backed by
 * the SECURITY DEFINER `case_action_items_kpis`, internally `is_staff_admin_of`-
 * gated and repointed to the hub (case-sourced rows). Returns zeroed counts for a
 * non-staff_admin (no leak). Signature unchanged.
 */
export async function getCaseActionItemKpis(
  commissionId: string,
): Promise<CaseActionItemKpis> {
  const zero: CaseActionItemKpis = { open: 0, overdue: 0, completedYtd: 0 }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('case_action_items_kpis', {
    p_commission_id: commissionId,
  })

  if (error || !data) return zero

  const row = (data as unknown as ActionItemKpisRow[])[0]
  if (!row) return zero

  return {
    open: Number(row.open),
    overdue: Number(row.overdue),
    completedYtd: Number(row.completed_ytd),
  }
}
