import { createClient } from '@/lib/supabase/server'

/**
 * Meeting ACTION ITEMS data-access (Phase 10 — Meetings; Architecture Rule 9 —
 * reads through `src/lib/queries/`). Mirrors `case_action_items`: a meeting's
 * action plan is a set of follow-up items with a light status lifecycle
 * (`open`/`in_progress`/`done`/`cancelled`), an optional assignee + due date, an
 * optional `source_agenda_item_id` (the agenda item that generated it,
 * `ON DELETE SET NULL`), and an optional `case_id` cross-link to a case. Unlike
 * the case variant, `commission_id` is DENORMALIZED on the row (for a direct RLS
 * predicate). RLS is member-read / staff_admin-write; assignees advance their
 * OWN items via a narrow RPC. Strings are pt-BR, resolved in the UI.
 *
 * CONTRACT STATUS (task B0): the body is a placeholder until the migrations land.
 */

/** Action-item lifecycle status (shared shape with cases). */
export type MeetingActionItemStatus =
  | 'open'
  | 'in_progress'
  | 'done'
  | 'cancelled'

/** One follow-up action item generated by a meeting. */
export interface MeetingActionItem {
  id: string
  meetingId: string
  /** Denormalized for RLS (the meeting's commission). */
  commissionId: string
  /** The agenda item that generated this, if any (`null` once it is deleted, or if free-standing). */
  sourceAgendaItemId: string | null
  /** Optional cross-link to a case this follow-up concerns; `null` if none. */
  caseId: string | null
  title: string
  description: string | null
  status: MeetingActionItemStatus
  assignedTo: string | null
  /** Assignee's display name (joined); `null` if unassigned/unresolved. */
  assignedToName: string | null
  /** ISO `YYYY-MM-DD`; `null` = no due date. Past + not done/cancelled = overdue. */
  dueDate: string | null
  createdBy: string | null
  createdAt: string
  updatedAt: string
  completedAt: string | null
  completedBy: string | null
}

// ---------------------------------------------------------------------------
// Reads — RLS-scoped (members read); BODY IS A PLACEHOLDER until migrations land.
// ---------------------------------------------------------------------------

interface MeetingActionItemRow {
  id: string
  meeting_id: string
  commission_id: string
  source_agenda_item_id: string | null
  case_id: string | null
  title: string
  description: string | null
  status: MeetingActionItemStatus
  assigned_to: string | null
  due_date: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  completed_at: string | null
  completed_by: string | null
  profiles: { full_name: string | null } | null
}

/**
 * The action items of one meeting (the per-meeting panel). RLS-scoped (members
 * read); `[]` when unreadable. Ordered: by due date (soonest first, nulls last),
 * then newest. The assignee's name is joined via the member-readable `profiles`.
 */
export async function listMeetingActionItems(
  meetingId: string,
): Promise<MeetingActionItem[]> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('meeting_action_items')
    .select(
      `id, meeting_id, commission_id, source_agenda_item_id, case_id, title,
       description, status, assigned_to, due_date, created_by, created_at,
       updated_at, completed_at, completed_by,
       profiles:assigned_to ( full_name )`,
    )
    .eq('meeting_id', meetingId)
    .order('due_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: false })
    .returns<MeetingActionItemRow[]>()

  if (error || !data) return []

  return data.map((r) => ({
    id: r.id,
    meetingId: r.meeting_id,
    commissionId: r.commission_id,
    sourceAgendaItemId: r.source_agenda_item_id,
    caseId: r.case_id,
    title: r.title,
    description: r.description,
    status: r.status,
    assignedTo: r.assigned_to,
    assignedToName: r.profiles?.full_name ?? null,
    dueDate: r.due_date,
    createdBy: r.created_by,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    completedAt: r.completed_at,
    completedBy: r.completed_by,
  }))
}
