import { createClient } from '@/lib/supabase/server'

/**
 * Meeting ACTION ITEMS data-access (Phase 10 — Meetings; Architecture Rule 9 —
 * reads through `src/lib/queries/`). A meeting's action plan is a set of
 * follow-up items with a light status lifecycle
 * (`open`/`in_progress`/`done`/`cancelled`), an optional assignee + due date, an
 * optional `source_agenda_item_id` (the agenda item that generated it,
 * `ON DELETE SET NULL`), and an optional `linked_case_id` cross-link to a case.
 * `commission_id` is DENORMALIZED on the row (for a direct RLS predicate).
 * RLS is member-read / staff_admin-write; assignees advance their OWN items via
 * a narrow RPC. Strings are pt-BR, resolved in the UI.
 *
 * Backed by the SHARED `public.action_items` hub (Option A unification): this
 * reads the `source_type='meeting'` rows and maps the joined status KEY into the
 * historical `MeetingActionItemStatus` union so the meetings UI is unchanged. The
 * exported types are stable; only the underlying table + status column changed.
 */

/** Action-item lifecycle status (shared shape with cases). */
export type MeetingActionItemStatus =
  | 'open'
  | 'in_progress'
  | 'done'
  | 'cancelled'

/** One follow-up action item generated by a meeting. */
export interface MeetingActionItem {
  id: string
  meetingId: string
  /** Denormalized for RLS (the meeting's commission). */
  commissionId: string
  /** The agenda item that generated this, if any (`null` once it is deleted, or if free-standing). */
  sourceAgendaItemId: string | null
  /** Optional cross-link to a case this follow-up concerns; `null` if none. */
  caseId: string | null
  title: string
  description: string | null
  status: MeetingActionItemStatus
  assignedTo: string | null
  /** Assignee's display name (joined); `null` if unassigned/unresolved. */
  assignedToName: string | null
  /** ISO `YYYY-MM-DD`; `null` = no due date. Past + not done/cancelled = overdue. */
  dueDate: string | null
  createdBy: string | null
  createdAt: string
  updatedAt: string
  completedAt: string | null
  completedBy: string | null
}

// ---------------------------------------------------------------------------
// Reads — RLS-scoped (members read); BODY IS A PLACEHOLDER until migrations land.
// ---------------------------------------------------------------------------

interface MeetingActionItemRow {
  id: string
  source_meeting_id: string | null
  commission_id: string
  source_agenda_item_id: string | null
  linked_case_id: string | null
  title: string
  description: string | null
  status: { key: string } | null
  assigned_to: string | null
  due_date: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  completed_at: string | null
  completed_by: string | null
  profiles: { full_name: string | null } | null
}

/** The four historical statuses; anything else falls back to `open`. */
const MEETING_ACTION_ITEM_STATUSES: readonly MeetingActionItemStatus[] = [
  'open',
  'in_progress',
  'done',
  'cancelled',
]

function toMeetingActionItemStatus(key: string | undefined): MeetingActionItemStatus {
  return (MEETING_ACTION_ITEM_STATUSES as readonly string[]).includes(key ?? '')
    ? (key as MeetingActionItemStatus)
    : 'open'
}

/**
 * The action items of one meeting (the per-meeting panel). Reads the shared
 * `action_items` hub filtered to this meeting's `source_type='meeting'` rows.
 * RLS-scoped (members read); `[]` when unreadable. Ordered: by due date (soonest
 * first, nulls last), then newest. The assignee's name is joined via the
 * member-readable `profiles`; the lifecycle status is the joined status KEY.
 */
export async function listMeetingActionItems(
  meetingId: string,
): Promise<MeetingActionItem[]> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('action_items')
    .select(
      `id, source_meeting_id, commission_id, source_agenda_item_id, linked_case_id, title,
       description, assigned_to, due_date, created_by, created_at,
       updated_at, completed_at, completed_by,
       status:status_id ( key ),
       profiles:assigned_to ( full_name )`,
    )
    .eq('source_type', 'meeting')
    .eq('source_meeting_id', meetingId)
    .order('due_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: false })
    .returns<MeetingActionItemRow[]>()

  if (error) {
    // A swallowed error here silently empties the panel for what is really a
    // broken query (e.g. 42703 after a column rename) — log it, then fail closed.
    console.error('[listMeetingActionItems] query failed', {
      meetingId,
      code: error.code,
      message: error.message,
      details: error.details,
      hint: error.hint,
    })
    return []
  }
  if (!data) return []

  return data.map((r) => ({
    id: r.id,
    meetingId: r.source_meeting_id ?? meetingId,
    commissionId: r.commission_id,
    sourceAgendaItemId: r.source_agenda_item_id,
    caseId: r.linked_case_id,
    title: r.title,
    description: r.description,
    status: toMeetingActionItemStatus(r.status?.key),
    assignedTo: r.assigned_to,
    assignedToName: r.profiles?.full_name ?? null,
    dueDate: r.due_date,
    createdBy: r.created_by,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    completedAt: r.completed_at,
    completedBy: r.completed_by,
  }))
}
