'use server'

import { revalidatePath } from 'next/cache'

import { createClient } from '@/lib/supabase/server'
import { ACCREDITATION_MESSAGES as MESSAGES, mapAccreditationError } from '@/lib/accreditation/messages'
import { findEvidenceCandidates } from '@/lib/queries/accreditation'
import type {
  ArtifactKind,
  AssessmentStatus,
  EvidenceCandidate,
  FrameworkStatus,
  StandardLevel,
} from '@/lib/accreditation/types'

/**
 * Standards Crosswalk & Readiness/Gap Engine v2 (Phase 16) server actions
 * (Architecture Rules 9–11; ADR 0093). Mirrors the
 * `src/lib/indicators/actions.ts` conventions: every write routes through a
 * SECURITY DEFINER RPC (the RPC is the sole authority, no client pre-check),
 * `useActionState`-shaped `{ ok, error?, fieldErrors? }`, pt-BR strings (Rule
 * 10), raw Postgres errors never reach the UI (mapped via
 * {@link mapAccreditationError}, `@/lib/accreditation/messages`).
 *
 * Guard order per ADR 0093 Wave 2 (Migration D): every write RPC opens with
 * `app.assert_accreditation_enabled()` (→ HC0Q9); `link_evidence` continues
 * flag → belongs (`app.artifact_belongs_to_commission`) → `can_read_case` /
 * `can_read_capa` for the restricted kinds → duplicate → insert.
 *
 * Every call below routes through `supabase.rpc(...)` typed against the real
 * generated `Database['public']['Functions']` entries (Migration C/D,
 * `20260903001200`/`20260903001300`, landed + `gen:types`-regenerated by
 * backend mid-Wave-2). An earlier revision of this file used a documented
 * `unknown`-cast adapter to write against the ADR/plan's prose-described RPC
 * shapes before the migrations landed; backend confirmed all param names
 * matched (4 needed small renames, applied) and the adapter is gone now that
 * the real types exist — see `914c9a3`/`025b9d7` history for the contract-
 * first sequencing this worked around.
 */

/** `useActionState`-shaped result (the indicators/action-items-hub convention). */
export interface ActionState {
  ok: boolean
  error?: string
  fieldErrors?: Record<string, string>
}

export interface CreateFrameworkState extends ActionState {
  frameworkId?: string
}

export interface CloneFrameworkState extends ActionState {
  frameworkId?: string
}

export interface UpsertStandardState extends ActionState {
  standardId?: string
}

export interface LinkEvidenceState extends ActionState {
  evidenceLinkId?: string
}

/** {@link searchEvidenceCandidates}'s result — the `onSearch` shape the picker component expects. */
export interface EvidenceCandidateSearchResult {
  ok: boolean
  error?: string
  candidates?: EvidenceCandidate[]
}

// ---------------------------------------------------------------------------
// Path revalidation
// ---------------------------------------------------------------------------

const ACCREDITATION_PATH = '/o/[org]/c/[commission]/manage/acreditacao'
const FRAMEWORK_PATH = '/o/[org]/c/[commission]/manage/acreditacao/[framework]'
const STANDARD_PATH =
  '/o/[org]/c/[commission]/manage/acreditacao/[framework]/padrao/[standard]'
const HOSPITAL_ACCREDITATION_PATH = '/o/[org]/manage/acreditacao'

function revalidateAccreditation(): void {
  revalidatePath(ACCREDITATION_PATH, 'page')
  revalidatePath(FRAMEWORK_PATH, 'page')
  revalidatePath(STANDARD_PATH, 'page')
}

function revalidateHospitalAccreditation(): void {
  revalidatePath(HOSPITAL_ACCREDITATION_PATH, 'page')
}

// --- form-field parsing helpers -------------------------------------------

function requiredString(formData: FormData, key: string): string {
  return String(formData.get(key) ?? '').trim()
}

function optionalString(formData: FormData, key: string): string | undefined {
  const value = requiredString(formData, key)
  return value || undefined
}

/**
 * A dedicated read for `note_md`-shaped fields backed by a `coalesce(p_x,
 * x)`-style RPC upsert (BUG-P16-001) — `optionalString`'s `'' -> undefined`
 * collapse makes "the user cleared this field" indistinguishable from "this
 * field was never in the submission" at the RPC boundary: `undefined` is
 * dropped from the JSON body entirely, so `coalesce(p_note_md, note_md)`
 * keeps the OLD value, silently discarding an intentional clear. This
 * preserves the distinction instead: a genuinely absent field (`formData.get`
 * returns `null` — not the case for an always-rendered textarea today, but
 * kept correct for a future conditional/disabled render) stays `undefined`
 * (RPC leaves the note untouched); a present-but-emptied field returns `''`
 * (RPC's `coalesce('', note_md)` overwrites with empty — an explicit clear).
 * Deliberately NOT a change to `optionalString` itself — every other caller
 * in this file (`version`/`description`/`descriptionMd`/`parentId`/`note`)
 * keeps the collapse; see the file-level BUG-P16-001 note on
 * `setStandardAssessment` for why only THIS field needed the distinction.
 */
function optionalClearableText(formData: FormData, key: string): string | undefined {
  const raw = formData.get(key)
  if (raw === null) return undefined
  return String(raw).trim()
}

function parseOptionalPosition(raw: FormDataEntryValue | null): number | undefined {
  const s = String(raw ?? '').trim()
  if (!s) return undefined
  const n = Number(s)
  return Number.isFinite(n) ? n : undefined
}

function parseOptionalLevel(raw: FormDataEntryValue | null): StandardLevel | undefined | null {
  const s = String(raw ?? '').trim()
  if (!s) return undefined
  const n = Number(s)
  return n === 1 || n === 2 || n === 3 ? (n as StandardLevel) : null // null = invalid
}

// ---------------------------------------------------------------------------
// Framework CRUD (Migration C — global: platform_admin only; custom: staff_admin_of(owner))
// ---------------------------------------------------------------------------

/**
 * Create a framework. `ownerCommissionId` empty/omitted = a global pack
 * (`app.is_admin()`-only per D6's one legitimate `is_admin` use — the
 * vocabulary/catalog arm); set = a commission-owned custom framework
 * (`is_staff_admin_of(owner)`). Routes to `create_framework`.
 */
export async function createFramework(
  _prev: CreateFrameworkState | undefined,
  formData: FormData,
): Promise<CreateFrameworkState> {
  const ownerCommissionId = optionalString(formData, 'ownerCommissionId')
  const key = requiredString(formData, 'key')
  const name = requiredString(formData, 'name')
  const version = optionalString(formData, 'version')
  const description = optionalString(formData, 'description')

  if (!key) return { ok: false, fieldErrors: { key: MESSAGES.keyRequired } }
  if (!name) return { ok: false, fieldErrors: { name: MESSAGES.nameRequired } }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('create_framework', {
    p_owner_commission: ownerCommissionId,
    p_key: key,
    p_name: name,
    p_version: version,
    p_description: description,
  })

  if (error || !data) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.frameworkCreated, frameworkId: data.id }
}

/** Edit a framework's own fields (not its standards). Routes to `update_framework`. */
export async function updateFramework(
  _prev: ActionState | undefined,
  formData: FormData,
): Promise<ActionState> {
  const id = requiredString(formData, 'frameworkId')
  const name = requiredString(formData, 'name')
  const version = optionalString(formData, 'version')
  const description = optionalString(formData, 'description')

  if (!id) return { ok: false, error: MESSAGES.frameworkNotFound }
  if (!name) return { ok: false, fieldErrors: { name: MESSAGES.nameRequired } }

  const supabase = await createClient()
  const { error } = await supabase.rpc('update_framework', {
    p_framework: id,
    p_name: name,
    p_version: version,
    p_description: description,
  })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.frameworkUpdated }
}

/** Archive or reactivate a framework. Routes to `set_framework_status`. */
export async function setFrameworkStatus(
  frameworkId: string,
  status: FrameworkStatus,
): Promise<ActionState> {
  if (!frameworkId) return { ok: false, error: MESSAGES.frameworkNotFound }

  const supabase = await createClient()
  const { error } = await supabase.rpc('set_framework_status', {
    p_framework: frameworkId,
    p_status: status,
  })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.frameworkStatusChanged }
}

/**
 * Clone a global (or another commission's — RLS forbids the latter in
 * practice) framework skeleton into a commission-owned, fully editable copy
 * (ADR 0093 D2/D9 — the clone is where a hospital pastes its own licensed
 * manual text). staff_admin-only; routes to `clone_framework`. Returns the
 * new framework id so the dialog can route straight to it.
 */
export async function cloneFramework(
  _prev: CloneFrameworkState | undefined,
  formData: FormData,
): Promise<CloneFrameworkState> {
  const frameworkId = requiredString(formData, 'frameworkId')
  const commissionId = requiredString(formData, 'commissionId')

  if (!frameworkId) return { ok: false, error: MESSAGES.frameworkNotFound }
  if (!commissionId) return { ok: false, error: MESSAGES.commissionNotFound }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('clone_framework', {
    p_framework: frameworkId,
    p_commission: commissionId,
  })

  if (error || !data) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.frameworkCloned, frameworkId: data.id }
}

// ---------------------------------------------------------------------------
// Standard CRUD (custom frameworks only — HC0QD rejects a global-pack write)
// ---------------------------------------------------------------------------

/**
 * Create or edit one standard (`standardId` present = edit). Routes to
 * `upsert_standard`. `level` is required only inside a leveled (ONA-shaped)
 * framework; leave empty for a non-leveled (JCI-shaped) one.
 */
export async function upsertStandard(
  _prev: UpsertStandardState | undefined,
  formData: FormData,
): Promise<UpsertStandardState> {
  const id = optionalString(formData, 'standardId')
  const frameworkId = requiredString(formData, 'frameworkId')
  const parentId = optionalString(formData, 'parentId')
  const code = requiredString(formData, 'code')
  const title = requiredString(formData, 'title')
  const descriptionMd = optionalString(formData, 'descriptionMd')
  const position = parseOptionalPosition(formData.get('position'))
  const level = parseOptionalLevel(formData.get('level'))

  if (!frameworkId) return { ok: false, error: MESSAGES.frameworkNotFound }
  if (!code) return { ok: false, fieldErrors: { code: MESSAGES.codeRequired } }
  if (!title) return { ok: false, fieldErrors: { title: MESSAGES.titleRequired } }
  if (level === null) return { ok: false, fieldErrors: { level: MESSAGES.levelInvalid } }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('upsert_standard', {
    p_id: id,
    p_framework: frameworkId,
    p_parent: parentId,
    p_code: code,
    p_title: title,
    p_description_md: descriptionMd,
    p_position: position,
    p_level: level,
  })

  if (error || !data) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.standardSaved, standardId: data.id }
}

/** Remove a standard (and, per the DB cascade, its evidence links/assessments). Routes to `delete_standard`. */
export async function deleteStandard(standardId: string): Promise<ActionState> {
  if (!standardId) return { ok: false, error: MESSAGES.standardNotFound }

  const supabase = await createClient()
  const { error } = await supabase.rpc('delete_standard', { p_standard: standardId })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.standardDeleted }
}

// ---------------------------------------------------------------------------
// Evidence (Migration D — staff_admin; guard order flag → belongs → read-cap → duplicate → insert)
// ---------------------------------------------------------------------------

/**
 * Link one artifact as evidence for a standard. `note` carries the standing
 * PHI-discouragement copy on its field (ADR 0093 D8) — enforced at the UI
 * layer (the standard panel), not here. Routes to `link_evidence`; HC0QA
 * (not linkable) / HC0QB (duplicate) map to the pt-BR messages in
 * `@/lib/accreditation/messages`.
 */
export async function linkEvidence(
  _prev: LinkEvidenceState | undefined,
  formData: FormData,
): Promise<LinkEvidenceState> {
  const commissionId = requiredString(formData, 'commissionId')
  const standardId = requiredString(formData, 'standardId')
  const artifactKind = requiredString(formData, 'artifactKind') as ArtifactKind
  const artifactId = requiredString(formData, 'artifactId')
  const note = optionalString(formData, 'note')

  if (!commissionId) return { ok: false, error: MESSAGES.commissionNotFound }
  if (!standardId) return { ok: false, error: MESSAGES.standardNotFound }
  if (!artifactKind) {
    return { ok: false, fieldErrors: { artifactKind: MESSAGES.artifactKindRequired } }
  }
  if (!artifactId) return { ok: false, fieldErrors: { artifactId: MESSAGES.artifactRequired } }

  const supabase = await createClient()
  const { data, error } = await supabase.rpc('link_evidence', {
    p_commission: commissionId,
    p_standard: standardId,
    p_kind: artifactKind,
    p_artifact: artifactId,
    p_note: note,
  })

  if (error || !data) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.evidenceLinked, evidenceLinkId: data.id }
}

/** Remove an evidence link. Routes to `unlink_evidence`. */
export async function unlinkEvidence(evidenceLinkId: string): Promise<ActionState> {
  if (!evidenceLinkId) return { ok: false, error: MESSAGES.evidenceLinkNotFound }

  const supabase = await createClient()
  const { error } = await supabase.rpc('unlink_evidence', { p_link: evidenceLinkId })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.evidenceUnlinked }
}

// ---------------------------------------------------------------------------
// Assessment (staff_admin upsert)
// ---------------------------------------------------------------------------

/**
 * Set (upsert) a commission's self-assessment for one standard. `noteMd`
 * carries the standing PHI-discouragement copy on its field (D8), enforced
 * at the UI layer. Routes to `set_standard_assessment`.
 *
 * BUG-P16-001 (data loss, fixed): the RPC's upsert does
 * `note_md = coalesce(p_note_md, note_md)` so a re-save with the note field
 * untouched preserves the existing note — but that same coalesce meant an
 * INTENTIONAL clear (empty the textarea, save) was indistinguishable from
 * "field not submitted" once `optionalString`'s `'' -> undefined` collapse
 * ran, so the clear silently no-opped instead of reaching the RPC. Fixed on
 * both sides: backend's RPC now treats `''` (not just non-null) as "set to
 * empty" vs `NULL`/omitted as "leave alone"; this action reads `noteMd` via
 * {@link optionalClearableText} instead of {@link optionalString} so an
 * emptied textarea sends `''` through, not `undefined`.
 */
export async function setStandardAssessment(
  _prev: ActionState | undefined,
  formData: FormData,
): Promise<ActionState> {
  const commissionId = requiredString(formData, 'commissionId')
  const standardId = requiredString(formData, 'standardId')
  const status = requiredString(formData, 'status') as AssessmentStatus
  const noteMd = optionalClearableText(formData, 'noteMd')

  if (!commissionId) return { ok: false, error: MESSAGES.commissionNotFound }
  if (!standardId) return { ok: false, error: MESSAGES.standardNotFound }
  if (!status) return { ok: false, fieldErrors: { status: MESSAGES.assessmentStatusRequired } }

  const supabase = await createClient()
  const { error } = await supabase.rpc('set_standard_assessment', {
    p_commission: commissionId,
    p_standard: standardId,
    p_status: status,
    p_note_md: noteMd,
  })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateAccreditation()
  return { ok: true, error: MESSAGES.assessmentSaved }
}

/* `getStandardAssessmentDetail` moved to `@/lib/queries/accreditation` (FUP-P16-2,
 * Architecture Rule 9). It was only ever here because `queries/accreditation.ts`
 * was still a `not implemented` stub when frontend needed it (BUG-P16-002) — debt,
 * not a design choice. Its one caller (the standard detail page) imports it from
 * the query layer directly; nothing needs a server-action wrapper, because a
 * Server Component can read the query layer itself. */

// ---------------------------------------------------------------------------
// Evidence candidate search (staff_admin DEFINER search feeding the picker)
// ---------------------------------------------------------------------------

/**
 * Candidate artifacts of one kind matching `query`, for the evidence picker's
 * debounced search (injected `onSearch`, mirroring
 * `src/components/responses/wizard/reference-picker.tsx`'s pattern). Per-kind
 * SELECTs inside the RPC already apply the reader's own visibility
 * (`can_read_case` / `can_read_capa`), so a candidate never appears if the
 * caller could not read it.
 *
 * This stays a server ACTION — its caller is `evidence-picker.tsx`, a Client
 * Component, which cannot reach the query layer directly — but the data access
 * itself now goes through `findEvidenceCandidates` (Architecture Rule 9,
 * FUP-P16-2). It used to call the RPC inline, with a comment explaining that
 * `queries/accreditation.ts` was still a `not implemented` stub and frontend
 * would not edit a backend-owned file. That stub is long since real, so the
 * reason expired; the comment outlived it.
 */
export async function searchEvidenceCandidates(
  commissionId: string,
  kind: ArtifactKind,
  query: string,
): Promise<EvidenceCandidateSearchResult> {
  if (!commissionId) return { ok: false, error: MESSAGES.commissionNotFound }

  const { candidates, error } = await findEvidenceCandidates(
    commissionId,
    kind,
    query,
  )
  if (error) return { ok: false, error: mapAccreditationError(error) }

  return { ok: true, candidates }
}

// ---------------------------------------------------------------------------
// Hospital ownership override (D7 — is_hospital_admin_of ONLY; org_admin may
// READ the hospital surface, Migration E, but is REJECTED here by the RPC
// itself, not by this action — the server enforces this regardless of what
// the UI shows)
// ---------------------------------------------------------------------------

/**
 * Set (or, with `commissionId: null`, clear) which commission's assessment is
 * the institutional answer for one standard at one hospital. Routes to
 * `set_standard_ownership`. Revalidates ONLY the hospital surface — the
 * ownership editor lives there exclusively.
 */
export async function setStandardOwnership(
  hospitalId: string,
  standardId: string,
  commissionId: string | null,
): Promise<ActionState> {
  if (!hospitalId) return { ok: false, error: MESSAGES.hospitalNotFound }
  if (!standardId) return { ok: false, error: MESSAGES.standardNotFound }

  const supabase = await createClient()
  const { error } = await supabase.rpc('set_standard_ownership', {
    p_hospital: hospitalId,
    p_standard: standardId,
    p_commission: commissionId ?? undefined,
  })

  if (error) return { ok: false, error: mapAccreditationError(error) }

  revalidateHospitalAccreditation()
  return {
    ok: true,
    error: commissionId ? MESSAGES.ownershipSet : MESSAGES.ownershipCleared,
  }
}

// NOTE: no type re-exports here — a `'use server'` module may export ONLY
// async server functions (the RSC action compiler rejects `export type {…}`).
// Consumers import the field-value unions (ArtifactKind / AssessmentStatus /
// …) directly from the pure `@/lib/accreditation/types`.
