#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bootstrap a git worktree for a second, parallel Claude Code session on this
# repo.
#
# WHY: `git worktree add` only gives you a second checkout on its own branch —
# it does NOT copy gitignored local state (.env.local, node_modules), and
# every worktree's `next dev` defaults to :3000, so two worktrees running
# `npm run dev` at once collide. This script does the rest: seed .env.local,
# install deps, pick a free port, and write a ./dev.sh wrapper so you don't
# have to remember the port every time. See docs/worktrees.md.
#
# USAGE (from anywhere inside this repo, including another worktree):
#   scripts/worktree-setup.sh <branch-name> [base-ref]
#
#   scripts/worktree-setup.sh feat/held-window-picker         # new branch off origin/main
#   scripts/worktree-setup.sh feat/held-window-picker origin/main
#   scripts/worktree-setup.sh existing-branch-already-local   # reuses it, no -b
#
# Creates the worktree under <repo-root>/worktrees/<branch-name>/ (gitignored
# — see .gitignore). Prints the assigned dev port and next steps when done.
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(git rev-parse --git-common-dir)/.." && pwd)"

BRANCH="${1:-}"
BASE_REF="${2:-origin/main}"
[ -n "$BRANCH" ] || { echo "USAGE: scripts/worktree-setup.sh <branch-name> [base-ref]" >&2; exit 1; }

WT_PATH="$ROOT/worktrees/$BRANCH"
[ -e "$WT_PATH" ] && { echo "FATAL: $WT_PATH already exists" >&2; exit 1; }

if git -C "$ROOT" show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "==> Adding worktree for existing local branch '$BRANCH'"
  git -C "$ROOT" worktree add "$WT_PATH" "$BRANCH"
else
  echo "==> Creating new branch '$BRANCH' off '$BASE_REF'"
  git -C "$ROOT" fetch origin --quiet || true
  git -C "$ROOT" worktree add -b "$BRANCH" "$WT_PATH" "$BASE_REF"
fi

cd "$WT_PATH"

# --- .env.local: gitignored, so a fresh worktree never has it ---
if [ -f "$ROOT/.env.local" ]; then
  cp "$ROOT/.env.local" .env.local
  echo "==> Copied .env.local from $ROOT"
elif [ -f "$ROOT/.env.example" ]; then
  cp "$ROOT/.env.example" .env.local
  echo "==> No .env.local at $ROOT — seeded from .env.example (fill in local Supabase keys, see 'supabase status')"
else
  echo "==> WARNING: no .env.local or .env.example found — create .env.local by hand before running the app" >&2
fi

# --- dependencies: node_modules is per-worktree, not shared ---
echo "==> npm install (separate node_modules for this worktree)"
npm install

# --- pick a free dev port so parallel worktrees don't collide on :3000 ---
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) IS_WIN=1 ;; *) IS_WIN=0 ;; esac
port_free() {
  local p="$1"
  if [ "$IS_WIN" = "1" ]; then
    ! netstat -ano 2>/dev/null | grep -q ":$p "
  elif command -v lsof >/dev/null 2>&1; then
    ! lsof -ti tcp:"$p" >/dev/null 2>&1
  else
    echo "WARNING: no lsof/netstat found — assuming port $p is free" >&2
    return 0
  fi
}
PORT=3000
while ! port_free "$PORT"; do PORT=$((PORT + 1)); done

cat > dev.sh <<EOF
#!/usr/bin/env bash
# Generated by scripts/worktree-setup.sh — runs this worktree's dev server on
# its assigned port (PORT can't be set via .env files; Next only reads it
# from the environment).
exec env PORT=$PORT npm run dev
EOF
chmod +x dev.sh

echo ""
echo "=================================================================="
echo "Worktree ready: $WT_PATH"
echo "Branch:         $BRANCH"
echo "Dev server:     ./dev.sh   ->  http://localhost:$PORT"
echo ""
echo "Local Supabase is a SHARED resource across all worktrees — don't run"
echo "'supabase start' / 'supabase db reset' from here unless you mean to"
echo "reset it for every worktree. See docs/worktrees.md."
echo ""
echo "Next:  cd worktrees/$BRANCH && claude"
echo "=================================================================="
