"use client";

import { useEffect, useId, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Lock } from "lucide-react";

import {
  createMeetingActionItem,
  updateMeetingActionItem,
  type ActionState,
  type CreateMeetingActionItemState,
  type MeetingActionItemInput,
} from "@/lib/meetings/actions";
import type { MeetingActionItem } from "@/lib/queries/meeting-action-items";
import type { MeetingAgendaItem } from "@/lib/queries/meetings";
import type { VisibilityScope } from "@/lib/queries/action-items";
import { VISIBILITY_SCOPE_LABEL } from "@/components/action-items/satellite-labels";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { FormBanner } from "@/components/auth/form-banner";
import { NativeSelect } from "@/components/ui/native-select";
import { DatePicker } from "@/components/ui/date-picker";
import type { LinkableCase } from "./case-linker";

const FIELD_CLASS =
  "w-full rounded-lg border border-input bg-card px-3 py-2 text-sm shadow-xs outline-none transition-[color,box-shadow,border-color] focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/40 disabled:cursor-not-allowed disabled:opacity-50";

/** Read-scope options, in the order shown in the select. */
const VISIBILITY_ORDER: VisibilityScope[] = [
  "committee",
  "case_restricted",
  "assignees_only",
];

/** An assignee option (commission member). */
export interface AssigneeOption {
  userId: string;
  name: string;
}

function formatCaseNumber(n: number): string {
  return `Caso ${String(n).padStart(4, "0")}`;
}

function caseLabelOf(c: LinkableCase): string {
  return `${formatCaseNumber(c.caseNumber)}${c.label ? ` — ${c.label}` : ""}`;
}

/**
 * Create / edit a meeting action item (F3) — a follow-up generated by the
 * meeting, optionally tied to an agenda item. Status changes go through the
 * advance/complete controls in the panel, not this form. staff_admin authors.
 *
 * Cross-link + visibility (ADR 0050, FE-2):
 *  - A `case_id` cross-link is CREATE-TIME ONLY (the hub UPDATE RPC has no
 *    `p_case_id`), so the case picker shows only on create; on edit the fixed
 *    link is rendered read-only.
 *  - The read scope (`committee` / `case_restricted` / `assignees_only`) is
 *    editable in both modes. HARD GUARD: `case_restricted` is selectable only
 *    when an effective case is present (the picker's value on create, or the
 *    item's fixed link on edit) — the RPC does NOT cross-validate, and a
 *    `case_restricted` row with no case is invisible to everyone incl. its
 *    creator, so the FE is the only guard.
 *  - `MeetingActionItem` does not project the stored scope, so the select
 *    defaults to the RPC-computed value (derived from the effective case); on
 *    edit the scope is submitted only when the coordinator explicitly changes it
 *    (else `null`, which the update RPC coalesces to "keep current" — so an
 *    untouched edit never clobbers a prior override).
 */
export function ActionItemForm({
  mode,
  open,
  onOpenChange,
  meetingId,
  item,
  assignees,
  agendaItems,
  cases,
}: {
  mode: "create" | "edit";
  open: boolean;
  onOpenChange: (open: boolean) => void;
  meetingId: string;
  /** Required for `edit`. */
  item?: MeetingActionItem;
  assignees: AssigneeOption[];
  agendaItems: MeetingAgendaItem[];
  /** Same-commission cases for the create-mode cross-link picker. */
  cases: LinkableCase[];
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [state, setState] = useState<
    (CreateMeetingActionItemState & ActionState) | null
  >(null);

  const [title, setTitle] = useState(item?.title ?? "");
  const [description, setDescription] = useState(item?.description ?? "");
  const [assignedTo, setAssignedTo] = useState(item?.assignedTo ?? "");
  const dueDateId = useId();
  const [dueDate, setDueDate] = useState(item?.dueDate ?? "");
  const [sourceAgendaItemId, setSourceAgendaItemId] = useState(
    item?.sourceAgendaItemId ?? "",
  );
  // Case cross-link — editable on create, fixed (read-only) on edit.
  const [caseId, setCaseId] = useState(item?.caseId ?? "");
  // Read scope — defaults to the RPC-computed value (case_restricted when a case
  // is linked, else committee), since the stored scope is not projected.
  const [visibilityScope, setVisibilityScope] = useState<VisibilityScope>(
    item?.caseId ? "case_restricted" : "committee",
  );
  // Whether the coordinator explicitly changed the scope — an untouched EDIT
  // submits `null` (keep current) so we never overwrite a prior override.
  const [scopeTouched, setScopeTouched] = useState(false);

  const [wasOpen, setWasOpen] = useState(false);
  if (open !== wasOpen) {
    setWasOpen(open);
    if (open) {
      setState(null);
      setTitle(item?.title ?? "");
      setDescription(item?.description ?? "");
      setAssignedTo(item?.assignedTo ?? "");
      setDueDate(item?.dueDate ?? "");
      setSourceAgendaItemId(item?.sourceAgendaItemId ?? "");
      setCaseId(item?.caseId ?? "");
      setVisibilityScope(item?.caseId ? "case_restricted" : "committee");
      setScopeTouched(false);
    }
  }

  // The case that governs scope: the picker on create, the fixed link on edit.
  const effectiveCaseId =
    mode === "create" ? caseId || null : (item?.caseId ?? null);
  const canRestrictToCase = effectiveCaseId != null;
  // Never render/submit case_restricted without an effective case (defense in
  // depth; the state transitions below also keep this invariant).
  const safeScope: VisibilityScope =
    visibilityScope === "case_restricted" && !canRestrictToCase
      ? "committee"
      : visibilityScope;

  useEffect(() => {
    if (state?.ok) {
      onOpenChange(false);
      router.refresh();
    }
  }, [state, onOpenChange, router]);

  function handleCaseChange(next: string) {
    setCaseId(next);
    setVisibilityScope((prev) => {
      // Clearing the case must drop case_restricted (the hard guard).
      if (!next) return prev === "case_restricted" ? "committee" : prev;
      // While the coordinator hasn't made an explicit choice, follow the
      // RPC-computed default (a linked case restricts to the case).
      return scopeTouched ? prev : "case_restricted";
    });
  }

  function handleScopeChange(next: VisibilityScope) {
    setScopeTouched(true);
    setVisibilityScope(next);
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    // Hard guard: never submit case_restricted without an effective case.
    const scope: VisibilityScope =
      safeScope === "case_restricted" && !canRestrictToCase
        ? "committee"
        : safeScope;
    const input: MeetingActionItemInput = {
      title: title.trim(),
      description: description.trim() || null,
      assignedTo: assignedTo || null,
      dueDate: dueDate || null,
      sourceAgendaItemId: sourceAgendaItemId || null,
      // Create sets the cross-link; on edit it is fixed (and the RPC ignores it).
      caseId: effectiveCaseId,
      // Create sends the chosen scope; edit sends it only when explicitly changed
      // (else null → the update RPC keeps the current scope).
      visibilityScope: mode === "create" ? scope : scopeTouched ? scope : null,
    };
    startTransition(async () => {
      const result =
        mode === "create"
          ? await createMeetingActionItem(meetingId, input)
          : await updateMeetingActionItem(item!.id, input);
      setState(result);
    });
  }

  const ordered = [...agendaItems].sort((a, b) => a.position - b.position);
  const linkedCase =
    mode === "edit" && item?.caseId
      ? (cases.find((c) => c.id === item.caseId) ?? null)
      : null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90svh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {mode === "create" ? "Novo item de ação" : "Editar item de ação"}
          </DialogTitle>
          <DialogDescription>
            Registre uma ação de acompanhamento decorrente desta reunião. Nunca
            inclua dados de paciente.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="flex flex-col gap-4" noValidate>
          {state && !state.ok && !state.fieldErrors?.title && (
            <FormBanner tone="error">{state.error}</FormBanner>
          )}

          <label className="flex flex-col gap-1.5 text-sm">
            <span className="font-medium">Título</span>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
              className={FIELD_CLASS}
              placeholder="Ex.: Revisar protocolo de higienização"
              aria-invalid={state?.fieldErrors?.title ? true : undefined}
            />
            {state?.fieldErrors?.title && (
              <span role="alert" className="text-sm font-medium text-destructive">
                {state.fieldErrors.title}
              </span>
            )}
          </label>

          <label className="flex flex-col gap-1.5 text-sm">
            <span className="font-medium">
              Descrição{" "}
              <span className="font-normal text-muted-foreground">
                (opcional)
              </span>
            </span>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className={FIELD_CLASS}
              placeholder="Detalhe a ação a ser tomada…"
            />
          </label>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <label className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">
                Responsável{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </span>
              <NativeSelect
                value={assignedTo}
                onChange={(e) => setAssignedTo(e.target.value)}
                className="py-2"
              >
                <option value="">Sem responsável</option>
                {assignees.map((a) => (
                  <option key={a.userId} value={a.userId}>
                    {a.name}
                  </option>
                ))}
              </NativeSelect>
            </label>

            <div className="flex flex-col gap-1.5 text-sm">
              <label
                id={`${dueDateId}-label`}
                htmlFor={dueDateId}
                className="font-medium"
              >
                Prazo{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </label>
              <DatePicker
                id={dueDateId}
                labelId={`${dueDateId}-label`}
                value={dueDate}
                onChange={setDueDate}
              />
            </div>
          </div>

          {ordered.length > 0 && (
            <label className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">
                Item de pauta de origem{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </span>
              <NativeSelect
                value={sourceAgendaItemId}
                onChange={(e) => setSourceAgendaItemId(e.target.value)}
                className="py-2"
              >
                <option value="">Nenhum</option>
                {ordered.map((a, i) => (
                  <option key={a.id} value={a.id}>
                    {i + 1}. {a.title}
                  </option>
                ))}
              </NativeSelect>
            </label>
          )}

          {/* Case cross-link. Create: a picker (same-commission cases). Edit: the
              fixed link, read-only (the update RPC cannot change it). */}
          {mode === "create" ? (
            cases.length > 0 && (
              <label className="flex flex-col gap-1.5 text-sm">
                <span className="font-medium">
                  Vínculo com caso{" "}
                  <span className="font-normal text-muted-foreground">
                    (opcional)
                  </span>
                </span>
                <NativeSelect
                  value={caseId}
                  onChange={(e) => handleCaseChange(e.target.value)}
                  className="py-2"
                >
                  <option value="">Sem vínculo</option>
                  {cases.map((c) => (
                    <option key={c.id} value={c.id}>
                      {caseLabelOf(c)}
                    </option>
                  ))}
                </NativeSelect>
                <span className="text-xs text-muted-foreground">
                  Ao vincular um caso, por padrão o item fica restrito a quem pode
                  ver o caso.
                </span>
              </label>
            )
          ) : item?.caseId ? (
            <div className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">Vínculo com caso</span>
              <div className="flex items-start gap-2 rounded-lg border border-border/70 bg-muted/20 px-3 py-2 text-xs text-muted-foreground">
                <Lock aria-hidden="true" className="mt-0.5 size-3.5 shrink-0" />
                <span>
                  <span className="font-medium text-foreground">
                    {linkedCase ? caseLabelOf(linkedCase) : "Caso vinculado"}
                  </span>{" "}
                  — o vínculo com o caso é definido na criação e não pode ser
                  alterado aqui.
                </span>
              </div>
            </div>
          ) : null}

          {/* Read scope. case_restricted is disabled without an effective case. */}
          <label className="flex flex-col gap-1.5 text-sm">
            <span className="font-medium">Visibilidade</span>
            <NativeSelect
              value={safeScope}
              onChange={(e) =>
                handleScopeChange(e.target.value as VisibilityScope)
              }
              className="py-2"
            >
              {VISIBILITY_ORDER.map((scope) => (
                <option
                  key={scope}
                  value={scope}
                  disabled={scope === "case_restricted" && !canRestrictToCase}
                >
                  {VISIBILITY_SCOPE_LABEL[scope]}
                </option>
              ))}
            </NativeSelect>
            <span className="text-xs text-muted-foreground">
              {canRestrictToCase
                ? "Define quem pode ver este item de ação."
                : "“Restrito ao caso” fica disponível quando há um caso vinculado."}
            </span>
          </label>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              size="lg"
              onClick={() => onOpenChange(false)}
              disabled={isPending}
            >
              Cancelar
            </Button>
            <Button type="submit" size="lg" disabled={isPending}>
              {isPending
                ? "Salvando…"
                : mode === "create"
                  ? "Criar item"
                  : "Salvar"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
