"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import {
  createMeetingActionItem,
  updateMeetingActionItem,
  type ActionState,
  type CreateMeetingActionItemState,
  type MeetingActionItemInput,
} from "@/lib/meetings/actions";
import type { MeetingActionItem } from "@/lib/queries/meeting-action-items";
import type { MeetingAgendaItem } from "@/lib/queries/meetings";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { FormBanner } from "@/components/auth/form-banner";

const FIELD_CLASS =
  "w-full rounded-lg border border-input bg-card px-3 py-2 text-sm shadow-xs outline-none transition-[color,box-shadow,border-color] focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/40 disabled:cursor-not-allowed disabled:opacity-50";

/** An assignee option (commission member). */
export interface AssigneeOption {
  userId: string;
  name: string;
}

/**
 * Create / edit a meeting action item (F3) — a follow-up generated by the
 * meeting, optionally tied to an agenda item. Status changes go through the
 * advance/complete controls in the panel, not this form. staff_admin authors.
 */
export function ActionItemForm({
  mode,
  open,
  onOpenChange,
  meetingId,
  item,
  assignees,
  agendaItems,
}: {
  mode: "create" | "edit";
  open: boolean;
  onOpenChange: (open: boolean) => void;
  meetingId: string;
  /** Required for `edit`. */
  item?: MeetingActionItem;
  assignees: AssigneeOption[];
  agendaItems: MeetingAgendaItem[];
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [state, setState] = useState<
    (CreateMeetingActionItemState & ActionState) | null
  >(null);

  const [title, setTitle] = useState(item?.title ?? "");
  const [description, setDescription] = useState(item?.description ?? "");
  const [assignedTo, setAssignedTo] = useState(item?.assignedTo ?? "");
  const [dueDate, setDueDate] = useState(item?.dueDate ?? "");
  const [sourceAgendaItemId, setSourceAgendaItemId] = useState(
    item?.sourceAgendaItemId ?? "",
  );

  const [wasOpen, setWasOpen] = useState(false);
  if (open !== wasOpen) {
    setWasOpen(open);
    if (open) {
      setState(null);
      setTitle(item?.title ?? "");
      setDescription(item?.description ?? "");
      setAssignedTo(item?.assignedTo ?? "");
      setDueDate(item?.dueDate ?? "");
      setSourceAgendaItemId(item?.sourceAgendaItemId ?? "");
    }
  }

  useEffect(() => {
    if (state?.ok) {
      onOpenChange(false);
      router.refresh();
    }
  }, [state, onOpenChange, router]);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const input: MeetingActionItemInput = {
      title: title.trim(),
      description: description.trim() || null,
      assignedTo: assignedTo || null,
      dueDate: dueDate || null,
      sourceAgendaItemId: sourceAgendaItemId || null,
      // Case cross-link is set elsewhere; not exposed in this form for v1.
      caseId: item?.caseId ?? null,
    };
    startTransition(async () => {
      const result =
        mode === "create"
          ? await createMeetingActionItem(meetingId, input)
          : await updateMeetingActionItem(item!.id, input);
      setState(result);
    });
  }

  const ordered = [...agendaItems].sort((a, b) => a.position - b.position);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90svh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {mode === "create" ? "Novo item de ação" : "Editar item de ação"}
          </DialogTitle>
          <DialogDescription>
            Registre uma ação de acompanhamento decorrente desta reunião. Nunca
            inclua dados de paciente.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="flex flex-col gap-4" noValidate>
          {state && !state.ok && !state.fieldErrors?.title && (
            <FormBanner tone="error">{state.error}</FormBanner>
          )}

          <label className="flex flex-col gap-1.5 text-sm">
            <span className="font-medium">Título</span>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
              className={FIELD_CLASS}
              placeholder="Ex.: Revisar protocolo de higienização"
              aria-invalid={state?.fieldErrors?.title ? true : undefined}
            />
            {state?.fieldErrors?.title && (
              <span role="alert" className="text-sm font-medium text-destructive">
                {state.fieldErrors.title}
              </span>
            )}
          </label>

          <label className="flex flex-col gap-1.5 text-sm">
            <span className="font-medium">
              Descrição{" "}
              <span className="font-normal text-muted-foreground">
                (opcional)
              </span>
            </span>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className={FIELD_CLASS}
              placeholder="Detalhe a ação a ser tomada…"
            />
          </label>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <label className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">
                Responsável{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </span>
              <select
                value={assignedTo}
                onChange={(e) => setAssignedTo(e.target.value)}
                className={FIELD_CLASS}
              >
                <option value="">Sem responsável</option>
                {assignees.map((a) => (
                  <option key={a.userId} value={a.userId}>
                    {a.name}
                  </option>
                ))}
              </select>
            </label>

            <label className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">
                Prazo{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </span>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className={FIELD_CLASS}
              />
            </label>
          </div>

          {ordered.length > 0 && (
            <label className="flex flex-col gap-1.5 text-sm">
              <span className="font-medium">
                Item de pauta de origem{" "}
                <span className="font-normal text-muted-foreground">
                  (opcional)
                </span>
              </span>
              <select
                value={sourceAgendaItemId}
                onChange={(e) => setSourceAgendaItemId(e.target.value)}
                className={FIELD_CLASS}
              >
                <option value="">Nenhum</option>
                {ordered.map((a, i) => (
                  <option key={a.id} value={a.id}>
                    {i + 1}. {a.title}
                  </option>
                ))}
              </select>
            </label>
          )}

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              size="lg"
              onClick={() => onOpenChange(false)}
              disabled={isPending}
            >
              Cancelar
            </Button>
            <Button type="submit" size="lg" disabled={isPending}>
              {isPending
                ? "Salvando…"
                : mode === "create"
                  ? "Criar item"
                  : "Salvar"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
