-- BUG-ACT-ACL-1 — `app.is_entitled_document_approver` gets an explicit EXECUTE ACL.
--
-- THE DEFECT. The function carried `proacl = NULL`, which is not "no grants" — it is
-- the Postgres DEFAULT for a function: EXECUTE to PUBLIC. Catalog-confirmed on a
-- quiet stack (the original reading was taken while a gate was mid-run, so it was
-- re-measured before this migration was written):
--
--   app.can_manage_professional(uuid,uuid)        postgres=X, authenticated=X, service_role=X
--   app.is_hospital_member_of(uuid)               postgres=X, authenticated=X, service_role=X
--   app.is_org_level_admin_within(uuid)           postgres=X, authenticated=X, service_role=X
--   app.is_org_member(uuid)                       postgres=X, authenticated=X, service_role=X
--   app.is_pqs_member_of_any(uuid)                postgres=X, authenticated=X, service_role=X
--   app.is_pqs_operator_in_org_for(uuid,uuid)     postgres=X, authenticated=X, service_role=X
--   app.is_quality_reviewer_in_org(uuid)          postgres=X, authenticated=X, service_role=X
--   app.is_entitled_document_approver(uuid,uuid)  <<NULL = PUBLIC>>   <-- the outlier
--
-- All 8 are the set `20260918001000` re-based; 7 carry the house idiom and this one
-- never did. NOT an ACT regression: Stage 2 used CREATE OR REPLACE, which left
-- NULL -> NULL exactly as intended. The gap predates it.
--
-- NOT DIRECTLY REACHABLE TODAY, WHICH IS WHY IT IS A HARDENING FIX AND NOT A P0.
-- `app` is not in `config.toml`'s exposed schemas, so PostgREST offers no route to
-- it. Its only in-database caller is `public.submit_document_for_approval` (catalog-
-- derived), which is SECURITY DEFINER owned by `postgres` — so it executes as the
-- owner and is unaffected by what PUBLIC may or may not do. Nothing legitimate loses
-- access here.
--
-- ONE INSTANCE OF A KNOWN POPULATION, NOT THE POPULATION. The standing
-- AUDIT-INVOKER-WRAPPER item (PROGRESS.md, "Remaining pre-pilot work") tracks the
-- broader set of `app` DEFINER functions carrying EXECUTE to PUBLIC. This migration
-- closes the one instance ACT surfaced by name so it is not re-discovered as though
-- it were new; it does NOT close that audit, and must not be read as having done so.
--
-- REVOKE-then-GRANT, not GRANT alone: with proacl NULL, Postgres materialises the
-- default ACL on first REVOKE (owner keeps EXECUTE, PUBLIC loses it). A bare GRANT
-- would materialise the ACL with PUBLIC's default EXECUTE still in it and change
-- nothing about the exposure. `anon` holds no explicit grant and inherits from
-- PUBLIC, so revoking PUBLIC covers it.

revoke all on function app.is_entitled_document_approver(uuid, uuid) from public;
grant execute on function app.is_entitled_document_approver(uuid, uuid)
  to authenticated, service_role;
