-- =============================================================================
-- PDF·P1 M2 — the printed-documents DEFINER doors (ADR 0104 D5/D6/D8/D11/D12;
-- plan §2.1 M2, lead-approved 2026-08-07 + Amendments A/B).
--
-- House door discipline (copied from the live set_case_visibility /
-- open_attachment bodies, read from pg_get_functiondef 2026-08-07): flag
-- assert first · AUTHORITY FIRST with its own SQLSTATE · validation after,
-- each distinct · explicit app.audit_write · REVOKE FROM PUBLIC then GRANT.
--
-- SQLSTATE block for this module (HC0D0 is taken by another domain —
-- catalog-checked): authority 42501 · flag check_violation · not-found P0002 ·
--   HC0D1 = validation (format / template coherence / reason vocabulary)
--   HC0D2 = PHI mint refused (no PHI-capable kind registered — fails closed)
--   HC0D3 = storage object missing at the derived path (Amendment B)
--   HC0D4 = uniqueness collision (token / short code / id — Amendment A: the
--           action retries the whole mint with fresh credentials)
--   HC0D5 = invalid state (already revoked)
--
-- AMENDMENT A (lead, 2026-08-07): the verification token + short code are
-- generated by the mint ACTION before payload build — the QR in the CANONICAL
-- bytes must carry the final /verificar/<token> URL, so a door-minted token
-- could never appear in the bytes it registers. The door VALIDATES format and
-- lets the unique constraints enforce uniqueness. Accepted residual (review
-- invariant): a direct RPC caller can choose his own format-valid token — it
-- degrades only his own document's verifiability (D2: faithfulness is
-- process-based).
--
-- AMENDMENT B (lead, 2026-08-07): the door verifies the storage OBJECT EXISTS
-- at the derived path before insert — a registry row must never point at a
-- missing object. (postgres holds grantable ALL on storage.objects —
-- catalog-verified; create_attachment is the live DEFINER precedent.)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Flag gate (the assert_response_correction_enabled idiom).
-- ---------------------------------------------------------------------------
create or replace function app.assert_document_printing_enabled()
returns void
language plpgsql
stable
set search_path to 'app', 'public', 'pg_catalog'
as $$
begin
  if not app.feature_enabled('document_printing') then
    raise exception 'a emissão de documentos em PDF não está disponível'
      using errcode = 'check_violation';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- mint_printed_document — D1/D5/D6/D11/D12.
-- Mint right ≡ source visibility (D11): the SAME dispatch the registry RLS
-- uses; not admin-gated (that is what the audit trail is for). platform_admin
-- holds no arm anywhere in the dispatch — denied by construction, keystoned.
--
-- Deviation 2 (lead-acked): NO p_storage_path parameter — the path is DERIVED
-- (std/<p_id>.pdf; phi/ from P3) and double-enforced by pd_storage_path_derived.
-- The action generates p_id, uploads to that exact path FIRST, then calls this
-- door; on RPC failure the action deletes the object (all-or-nothing, D5).
-- ---------------------------------------------------------------------------
create or replace function public.mint_printed_document(
  p_id uuid,
  p_source_kind text,
  p_source_id uuid,
  p_template_key text,
  p_template_version int,
  p_content_hash text,
  p_verification_token text,
  p_verification_short_code text,
  p_contains_phi boolean default false
) returns public.printed_documents
language plpgsql
security definer
set search_path to 'app', 'public', 'pg_catalog'
as $$
declare
  v_uid uuid := auth.uid();
  v_commission uuid;
  v_storage_path text;
  v_row public.printed_documents;
begin
  perform app.assert_document_printing_enabled();

  -- AUTHORITY FIRST (M1·4 order): mint right ≡ source visibility (D11).
  -- A null uid falls out here too (the dispatch fails closed on null).
  if not app.can_view_printed_document(p_source_kind, p_source_id, v_uid) then
    raise exception 'sem autorização para emitir um documento deste registro'
      using errcode = '42501';
  end if;

  -- P1: no PHI-capable kind is registered — a PHI mint FAILS CLOSED (D9).
  -- P3 replaces this with the source domain's own PHI door delegation.
  if coalesce(p_contains_phi, false) then
    raise exception 'este tipo de documento não permite emissão com dados de paciente'
      using errcode = 'HC0D2';
  end if;

  -- Template coherence: the registered template set per kind (P1: forms only).
  if p_source_kind = 'form_response' and p_template_key <> 'form_response' then
    raise exception 'modelo de documento inválido para este tipo de registro'
      using errcode = 'HC0D1';
  end if;

  -- Amendment A: credential FORMAT is door-enforced; generation is the
  -- action's (the token must be inside the canonical bytes' QR).
  -- Token: URL-safe base64 alphabet, >= 32 chars (>= 192 bits).
  if p_verification_token is null
     or p_verification_token !~ '^[A-Za-z0-9_-]{32,128}$' then
    raise exception 'token de verificação em formato inválido'
      using errcode = 'HC0D1';
  end if;
  -- Short code: exactly 10 chars of the unambiguous alphabet (no I/O/0/1).
  if p_verification_short_code is null
     or p_verification_short_code !~ '^[A-HJ-NP-Z2-9]{10}$' then
    raise exception 'código de verificação em formato inválido'
      using errcode = 'HC0D1';
  end if;

  -- Owning commission, per kind (only reachable for kinds whose visibility
  -- arm exists — everything else already failed the authority check above).
  if p_source_kind = 'form_response' then
    select commission_id into v_commission
    from public.responses where id = p_source_id;
  end if;
  if v_commission is null then
    raise exception 'registro de origem não encontrado'
      using errcode = 'HC0D1';
  end if;

  v_storage_path :=
    (case when p_contains_phi then 'phi/' else 'std/' end) || p_id::text || '.pdf';

  -- AMENDMENT B: the object must already exist at the derived path — a
  -- registry row never points at a missing object (upload-before-mint, D5).
  if not exists (
    select 1 from storage.objects
    where bucket_id = 'printed-documents' and name = v_storage_path
  ) then
    raise exception 'objeto de armazenamento ausente para esta emissão'
      using errcode = 'HC0D3';
  end if;

  -- Supersession (D6) + insert, atomically in this transaction.
  -- SUPERSEDE_ACTIVE: the registry always knows the current print.
  update public.printed_documents
     set status = 'superseded', superseded_at = now()
   where source_kind = p_source_kind
     and source_id = p_source_id
     and template_key = p_template_key
     and status = 'active';

  begin
    insert into public.printed_documents (
      id, source_kind, source_id, commission_id, template_key, template_version,
      content_hash, storage_path, contains_phi, status,
      verification_token, verification_short_code, minted_by
    ) values (
      p_id, p_source_kind, p_source_id, v_commission, p_template_key,
      p_template_version, p_content_hash, v_storage_path,
      coalesce(p_contains_phi, false), 'active',
      p_verification_token, p_verification_short_code, v_uid
    )
    returning * into v_row;
  exception
    when unique_violation then
      -- Amendment A: distinct code — the action re-mints with fresh
      -- credentials (full re-render; the short code is in the bytes).
      raise exception 'colisão de identificador de verificação — repita a emissão'
        using errcode = 'HC0D4';
  end;

  perform app.audit_write(
    'document.minted', 'printed_document', p_id, v_commission,
    'Documento PDF emitido',
    jsonb_build_object(
      'source_kind', p_source_kind,
      'source_id', p_source_id,
      'template_key', p_template_key,
      'template_version', p_template_version,
      'contains_phi', coalesce(p_contains_phi, false),
      'content_hash', p_content_hash));

  return v_row;
end;
$$;

revoke all on function public.mint_printed_document(uuid, text, uuid, text, int, text, text, text, boolean) from public;
grant execute on function public.mint_printed_document(uuid, text, uuid, text, int, text, text, text, boolean)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- open_printed_document — D8/D11/D12. The ONLY byte path: the serving route
-- calls this (authorize + audit), then streams via service-role Storage.
-- Download right is re-evaluated at CALL time (lose source access, lose its
-- PDFs — minting is not a permanent self-grant).
--
-- open_attachment idiom: not-found / out-of-scope → return NO ROW, no audit.
-- Deviation 3 (lead-acked): overlay_applied is COMPUTED here
-- (status <> 'active'), never caller-supplied — non-spoofable.
-- ---------------------------------------------------------------------------
create or replace function public.open_printed_document(p_id uuid)
returns table (storage_path text, status text, contains_phi boolean)
language plpgsql
security definer
set search_path to 'app', 'public', 'pg_catalog'
as $$
declare
  v_row public.printed_documents;
  v_overlay boolean;
begin
  perform app.assert_document_printing_enabled();

  select * into v_row from public.printed_documents where id = p_id;
  if v_row.id is null then
    return;                          -- not found: no row, no audit
  end if;
  -- OPEN_AUTHORITY: download follows CURRENT source access (D11).
  if not app.can_view_printed_document(v_row.source_kind, v_row.source_id, auth.uid()) then
    return;                          -- out of scope: no row, no audit
  end if;

  v_overlay := (v_row.status <> 'active');

  -- Every re-serve is audited (D12) — a download of another member's document
  -- is precisely Rule 11's read-of-another's-data. Records THAT + WHO, never
  -- content.
  perform app.audit_write(
    'document.downloaded', 'printed_document', p_id, v_row.commission_id,
    'Documento PDF baixado',
    jsonb_build_object('overlay_applied', v_overlay, 'status', v_row.status));

  return query select v_row.storage_path, v_row.status, v_row.contains_phi;
end;
$$;

revoke all on function public.open_printed_document(uuid) from public;
grant execute on function public.open_printed_document(uuid)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- revoke_printed_document — D6/D11/D12. A governance act, NOT undo: authority
-- is staff_admin of the owning commission + the admin chain — NEVER the minter
-- qua minter, never platform_admin (no arm). Nothing is deleted; verification
-- starts answering "revogado" and downloads gain the ANULADO overlay (D8).
-- ---------------------------------------------------------------------------
create or replace function public.revoke_printed_document(
  p_id uuid,
  p_reason_class text,
  p_reason text
) returns public.printed_documents
language plpgsql
security definer
set search_path to 'app', 'public', 'pg_catalog'
as $$
declare
  v_row public.printed_documents;
begin
  perform app.assert_document_printing_enabled();

  select * into v_row from public.printed_documents where id = p_id;
  if v_row.id is null then
    raise exception 'documento não encontrado' using errcode = 'P0002';
  end if;

  -- REVOKE_AUTHORITY first (M1·4 order).
  if not (app.is_staff_admin_of_for(v_row.commission_id, auth.uid())
          or app.is_commission_admin_of_for(v_row.commission_id, auth.uid())) then
    raise exception 'apenas a coordenação da comissão pode anular um documento emitido'
      using errcode = '42501';
  end if;

  if p_reason_class is null
     or p_reason_class not in ('wrong_data', 'minted_in_error', 'other') then
    raise exception 'classe de motivo de anulação inválida'
      using errcode = 'HC0D1';
  end if;
  -- Mandatory free-text reason (D6). PHI-FREE by instruction in the revoke
  -- dialog — governance text about the record, never source content.
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'o motivo da anulação é obrigatório'
      using errcode = 'HC0D1';
  end if;
  if v_row.status = 'revoked' then
    raise exception 'este documento já foi anulado'
      using errcode = 'HC0D5';
  end if;

  update public.printed_documents
     set status = 'revoked',
         revoked_at = now(),
         revoked_by = auth.uid(),
         revoked_reason_class = p_reason_class,
         revoked_reason = p_reason
   where id = p_id
   returning * into v_row;

  -- D12 records reason class + free text (the ADR's explicit spec for this
  -- event; the reason is PHI-free governance text about the record).
  perform app.audit_write(
    'document.revoked', 'printed_document', p_id, v_row.commission_id,
    'Documento PDF anulado',
    jsonb_build_object('reason_class', p_reason_class, 'reason', p_reason));

  return v_row;
end;
$$;

revoke all on function public.revoke_printed_document(uuid, text, text) from public;
grant execute on function public.revoke_printed_document(uuid, text, text)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- lookup_printed_document — the D10 public verification answer, deliberately
-- ANEMIC: authentic yes/no · status · mint date · kind · hospital name. NEVER
-- patient anything, case numbers, actor names, or bytes.
--
-- Deviation 4 (lead-acked): EXECUTE is SERVICE_ROLE ONLY — an anon-executable
-- PostgREST RPC would bypass the route's rate limiter entirely. The /verificar
-- pages are server-rendered and call through the admin client AFTER an
-- app-layer rate limit (which must front EVERY call path — lead requirement
-- 4b). p_viewer exists because a service-role call carries no auth.uid(): the
-- server passes the session uid it verified itself; document_id is non-null
-- ONLY when p_viewer passes the source-visibility dispatch (the "authenticated
-- user proceeds to the normal audited download" hook — no bytes, no path).
-- ---------------------------------------------------------------------------
create or replace function public.lookup_printed_document(
  p_credential text,
  p_viewer uuid default null
) returns table (
  matched boolean,
  status text,
  minted_at timestamptz,
  source_kind text,
  hospital_name text,
  document_id uuid
)
language plpgsql
security definer
set search_path to 'app', 'public', 'pg_catalog'
as $$
declare
  v_row public.printed_documents;
  v_hospital text;
begin
  perform app.assert_document_printing_enabled();

  if p_credential is null or btrim(p_credential) = '' then
    return query select false, null::text, null::timestamptz, null::text, null::text, null::uuid;
    return;
  end if;

  select pd.* into v_row
  from public.printed_documents pd
  where pd.verification_token = btrim(p_credential)
     or pd.verification_short_code = upper(btrim(p_credential))
  limit 1;

  -- Every lookup is logged (D12) — credential HASH only, never the raw token.
  insert into public.verification_lookups (source_kind, token_hash, matched)
  values (
    v_row.source_kind,     -- null when nothing matched
    encode(extensions.digest(left(btrim(p_credential), 512), 'sha256'), 'hex'),
    v_row.id is not null);

  if v_row.id is null then
    return query select false, null::text, null::timestamptz, null::text, null::text, null::uuid;
    return;
  end if;

  select h.name into v_hospital
  from public.commissions c
  join public.hospitals h on h.id = c.hospital_id
  where c.id = v_row.commission_id;

  return query select
    true,
    v_row.status,
    v_row.minted_at,
    v_row.source_kind,
    v_hospital,
    -- LOOKUP_VIEWER_GATE: the registry id only for a verified session that
    -- passes source visibility; anonymous callers ALWAYS get null (D10).
    case
      when p_viewer is not null
       and app.can_view_printed_document(v_row.source_kind, v_row.source_id, p_viewer)
      then v_row.id
      else null
    end;
end;
$$;

revoke all on function public.lookup_printed_document(text, uuid) from public;
grant execute on function public.lookup_printed_document(text, uuid) to service_role;
