-- Phase 7 / B7: enable the multi-phase cases feature.
--
-- The Phase-7 equivalent of the sign-off enforcement flip (migration
-- 20260613090001, ADR 0004): a one-line, data-only, forward-only flag flip. It
-- adds no tables, policies, or code, and does NOT edit any applied migration —
-- 20260613090004 inserted cases_multi_phase = false on purpose; this turns it ON.
--
-- Every Phase-7 cases RPC has gated app.feature_enabled('cases_multi_phase') at
-- entry since 20260613090005, raising a clean "feature unavailable" while OFF.
-- Flipping the flag here makes the feature exercisable for frontend's manual
-- verification and the tester's E2E, and is the state Phase 7 ships in. See
-- docs/decisions/0017-multi-phase-cases.md.
update app.feature_flags set enabled = true where key = 'cases_multi_phase';
