-- WS-2 MINOR-5: revoke TRUNCATE on the two membership tables from `authenticated`.
--
-- Mirrors C-1 (`20260711000100_grant_hardening.sql`), which revoked TRUNCATE (+
-- INSERT/UPDATE/DELETE) on `audit_log` from `authenticated`. WS-1
-- (`20260711000000_membership_lockdown.sql` era) already revoked
-- insert/update/delete on `organization_members` and `pqs_members` from
-- `authenticated` (every write now flows through guarded DEFINER RPCs), but left
-- the TRUNCATE grant untouched — latent (no exposed raw-SQL/TRUNCATE door reaches
-- `authenticated` in practice) but inconsistent with the audit_log posture, so we
-- close it for consistency.
revoke truncate on public.organization_members, public.pqs_members from authenticated;
