-- =============================================================================
-- FF-5 (ADR 0091) — Entity Reference, part 7 of 7: THE GATE FLIP.
--
-- The second half of the TWO-MIGRATION FLAG CONVENTION. The flag is SEEDED OFF
-- by its schema migration (20260902000000, part 1) so every migration between
-- there and here lands dark; this file — authored at the FF-5 gate, once the
-- phase is proven — turns it on.
--
-- ⚠ WHY THIS FILE IS NOT OPTIONAL, AND WHY IT HAS ITS OWN MIGRATION.
--
-- `supabase db push` carries MIGRATIONS. It does NOT carry `seed.sql` — that is
-- applied by `db reset` on a local/CI stack and never runs against production.
-- So a flag that is switched on only in `seed.sql` is ON for every developer and
-- every E2E run, and OFF in production. The phase then ships, passes its gate
-- green on local, deploys — and is INVISIBLE to the customer, with no error, no
-- log line and nothing to grep for. The feature simply is not there.
--
-- That is not a hypothetical. It shipped TWICE and was caught at review both
-- times: FF-2 round 1 blocker B-3, then FF-3 round 1 blocker B-1, one phase
-- later, in the same team, with the FF-2 finding already written down. Twice is
-- the reason this is now a convention with its own file rather than a line
-- someone is supposed to remember: an absent migration is VISIBLE (the file is
-- not there), while an absent line inside a 2500-line seed is not.
--
-- ⚠ RESOLVE THE VALUE, NOT THE NOUN. `app.feature_flags.description` is prose
-- and can say anything; `app.feature_flags.enabled` is the gate. Every reader
-- checking whether FF-5 is live must select `enabled`, not read a description, a
-- comment, or this header (ADR 0078 — "six ways text is not truth", of which a
-- flag's description versus its enabled column was one).
--
-- Idempotent: a plain UPDATE by key. Re-running is a no-op, and it cannot create
-- the row — if part 1 did not land, this affects zero rows rather than silently
-- inventing a flag with a different description.
--
-- SQLSTATE: allocates none.
-- =============================================================================

update app.feature_flags set enabled = true where key = 'entity_refs';
