-- ============================================================================
-- Flip `item_validations` ON permanently — the FF-3 gate flip (the same
-- two-migration convention as the FF-2 flip 20260830001200, the FF-1 flip
-- 20260828000900, the ADR-0085 case_corrections flip 20260825000600, the
-- ADR-0084 cases_bulk_create flip 20260824000000 and the ADR-0083
-- case_custom_fields flip 20260822000000). Seeded OFF in 20260901000000; this is
-- the deliberate permanent go-live flip.
--
-- ⚠ WHY THIS MIGRATION EXISTS (QA r1, B-1) — and it is the SECOND time, which is
-- the part worth reading. This is verbatim FF-2 r1's blocker B-3. Without it the
-- flag is ON only via `supabase/seed.sql:2125`, and `supabase db push` carries
-- migrations, not the seed. `db reset` (which applies the seed) is destructive and
-- will not be run against the data-bearing pilot database, so local dev and the
-- entire E2E gate are green *because the seed turns it on* while the pilot
-- deployment would have had `enabled = false`.
--
-- FF-3's flag-off behaviour is worse than FF-2's, and the difference is the reason
-- this is BLOCKING rather than a follow-up. Measured on the live stack, flag off,
-- against a form carrying only a LEGACY `form_items.config` bound:
--
--     get_response_validation_errors(resp)  ->  0 rows
--     submit_response(resp)                 ->  raises HC061
--
-- `app.assert_item_bounds` is NOT flag-gated (it predates FF-3 by phases) while
-- the error surface IS. So with the flag off **Amendment 1 inverts**: the submit
-- is refused and the list the wizard reads comes back empty — "blocked, with
-- nothing shown", which is the exact failure Amendment 1 was written to close.
-- Flag on, the same probe returns 1 row alongside the same HC061. The feature
-- being dark is therefore not merely "FF-3 is absent"; it actively degrades a
-- path that worked before FF-3 existed.
--
-- FF-3 Validation Engine (ADR 0090 + Amendments 1-4) is complete: the six-type
-- rule vocabulary behind an allowlist CHECK and a coverage trigger, the
-- `set_item_validations` DEFINER door with the two door-parity policy arms and the
-- SELECT-only grant, `form_items.required_if` composed into both arms of both
-- required-ness traversals with visibility winning structurally, the
-- `app.eval_validation` / `evalValidation` mirrored pair under golden vectors, the
-- single `app.response_validation_errors` walker that the HC0P9 submit gate and
-- `get_response_validation_errors` share, the widened operator authorability and
-- its publish-time arms, and the clone + Rule 5 coverage.
--
-- This flip gates AUTHORING (`set_item_validations` -> HC0Q0), the `required_if`
-- layer in all four required-ness traversals (passed as `null` while off), the
-- HC0P9 submit gate, and the error surface. Stored rows are unaffected in either
-- direction: turning the flag off never deletes a rule, it only stops consulting
-- them.
--
-- seed.sql additionally forces it ON for local/E2E (redundant here; keeps the two
-- paths honest — a seed regression then fails loudly rather than silently skipping
-- the flag-guarded keystones, per pgTAP 274 §0).
-- ============================================================================

update app.feature_flags set enabled = true where key = 'item_validations';
