-- ACT Stage 3 — drop the unreachable 3-arg app.has_role overload.
--
-- Coordinator ruling: the diff-scoped door sweep's BLIND finding on
-- `app.has_role(p_scope_type text, p_scope_id uuid, p_role text)` is in
-- scope for this stage even though its own text was never modified —
-- Stage 3 changed what the 4-arg has_role MEANS (added the caller-only hat
-- condition) without changing the 3-arg wrapper's text, and the 3-arg form
-- is a pure delegation to the 4-arg (`select app.has_role(p_scope_type,
-- p_scope_id, p_role, (select auth.uid()));`) — always a caller check, now
-- inheriting the hat condition transitively. An allowlist would be wrong
-- (CLAUDE.md §6 permits allowlisting only an UNREACHABLE backstop, and a
-- keystone would need a real call path). Ruling: keystone it, or drop it if
-- genuinely unreachable.
--
-- Genuinely unreachable, proven by call-site evidence, not assumed:
--   - A balanced-paren, comment-stripped sweep of ALL 928 functions in
--     app/public (the same corpus the is_admin() sweep used) found ZERO
--     calls to `has_role(...)` with exactly 3 arguments. All 21 real
--     has_role calls in the corpus use the 4-arg form (is_org_admin_of,
--     is_staff_admin_of, is_tenancy_admin_of_for, ... — the `is_*`
--     wrapper family the codebase actually adopted).
--   - `pg_policies` (all schemas): zero policies reference `has_role` at
--     all, 3-arg or 4-arg — every policy goes through an `is_*` wrapper.
--   - `supabase/seed.sql`, `supabase/demo/**`: zero references.
--   - `src/**` (TypeScript): zero `.rpc()` or query-builder references (the
--     3 grep hits found are documentation PROSE citing the predicate by
--     name in a comment, not a call — and `app` is not exposed to
--     PostgREST regardless, so no client-side call could ever reach it).
--   - Its own origin migration (20260720000100_has_role_predicate_family.sql,
--     read for historical narrative only, never as truth per the binding
--     catalog rule) names it "3-arg convenience overload... for policy
--     context" — a convenience the codebase never actually adopted; the
--     `is_*`/`is_*_of_for` wrapper family became the real calling
--     convention instead.
--
-- Dropping removes the BLIND finding at its root rather than guarding a
-- door nothing opens. The 4-arg has_role (the one every real caller uses,
-- and the one this stage's revert-twin keystone directly exercises) is
-- untouched by this migration.
drop function app.has_role(p_scope_type text, p_scope_id uuid, p_role text);
